/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface AccountingBody2 {
  /** @nullable */
  percent?: string | null;
  /** @nullable */
  savinsRate?: string | null;
  /** @nullable */
  year1?: string | null;
  /** @nullable */
  year2?: string | null;
  /** @nullable */
  year3?: string | null;
}
