/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { AccountingBody1 } from './accountingBody1';
import type { AccountingBody2 } from './accountingBody2';
import type { Head1 } from './head1';

/**
 * 家庭收支調查
 */
export interface AccountingStatisticsData {
  /** @nullable */
  body1?: AccountingBody1[] | null;
  /** @nullable */
  body2?: AccountingBody2[] | null;
  head1?: Head1;
}
