/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 活動量分析 - 数据
 */
export interface ActivityData {
  /** 預計 */
  book?: number;
  /** 實際 */
  complete?: number;
  /** 達成率 */
  percent?: number;
  /**
   * 進度
   * @nullable
   */
  progress?: string | null;
}
