/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { ActionLog } from './actionLog';
import type { PagingInfo } from './pagingInfo';

export interface ActionLogDataWithPageInfo {
  /** @nullable */
  datas?: ActionLog[] | null;
  /** @nullable */
  message?: string | null;
  pageInfo?: PagingInfo;
}
