/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 使用记录(依人/次数)
 */
export interface ActionLogStatistics {
  /** @nullable */
  action?: string | null;
  /** @nullable */
  description?: string | null;
  total?: number;
}
