/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { Activity } from './activity';

export interface ActivityListJsonData {
  code?: number;
  /** @nullable */
  data?: Activity[] | null;
  /** @nullable */
  message?: string | null;
  status?: boolean;
}
