/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { ActionLogStatistics } from './actionLogStatistics';
import type { PagingInfo } from './pagingInfo';

export interface ActionLogStatisticsDataWithPageInfo {
  /** @nullable */
  datas?: ActionLogStatistics[] | null;
  /** @nullable */
  message?: string | null;
  pageInfo?: PagingInfo;
}
