/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface ActionLogPackageQueryModel {
  /**
   * 功能
   * @nullable
   */
  action?: string | null;
  /**
   * IP
   * @nullable
   */
  clientIP?: string | null;
  /**
   * 說明
   * @nullable
   */
  description?: string | null;
  /**
   * 迄日
   * @nullable
   */
  endDate?: string | null;
  /** 企業別代號 */
  entGid: number;
  /** 是旧版数据 */
  isOldVersionData: boolean;
  /**
   * 帳號
   * @nullable
   */
  memberID?: string | null;
  /** 页码 */
  pageNum: number;
  /** 過濾昇華IP */
  skipGoUp: boolean;
  /**
   * 起日
   * @nullable
   */
  startDate?: string | null;
}
