/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface ActionLog {
  /**
   * @minLength 0
   * @maxLength 50
   */
  action: string;
  /**
   * @minLength 0
   * @maxLength 16
   * @nullable
   */
  appName?: string | null;
  /**
   * @minLength 0
   * @maxLength 24
   */
  clientIP: string;
  createTime?: string;
  /** @nullable */
  cstmId?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  entGid?: number | null;
  id?: number;
  /**
   * @minLength 0
   * @maxLength 16
   */
  memberID: string;
  /**
   * @minLength 0
   * @maxLength 128
   * @nullable
   */
  params?: string | null;
}
