/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface ActionLogS {
  /**
   * Controller名字.Action名字 注意不是接口名称 正确参考举例: Auth.SaveInsuredSetting
   * @minLength 0
   * @maxLength 50
   */
  action: string;
  /**
   * 描述
   * @minLength 1
   */
  description: string;
  /**
   * 参数以JSON字符串格式存储
   * @minLength 0
   * @maxLength 128
   * @nullable
   */
  params?: string | null;
}
