/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { CodeArea } from './codeArea';

/**
 * 地址
 */
export interface Address {
  /**
   * 鄉鎮市區
   * @minLength 0
   * @maxLength 50
   * @nullable
   */
  area?: string | null;
  /**
   * 鄉鎮市區
   * @nullable
   */
  areaList?: CodeArea[] | null;
  /**
   * 縣市名稱
   * @minLength 0
   * @maxLength 50
   * @nullable
   */
  city?: string | null;
  /**
   * 投遞範圍
   * @minLength 0
   * @maxLength 50
   * @nullable
   */
  deliveryRange?: string | null;
  id?: number;
  /**
   * 郵遞區號
   * @minLength 0
   * @maxLength 10
   * @nullable
   */
  postalCode?: string | null;
  /**
   * 原始路名
   * @minLength 0
   * @maxLength 50
   * @nullable
   */
  road?: string | null;
}
