/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface AddValueExpireDate {
  /** @nullable */
  agExpireDate?: string | null;
  /**
   * BO
   * @nullable
   */
  boExpireDate?: string | null;
  /**
   * CW
   * @nullable
   */
  cwExpireDate?: string | null;
  /**
   * FDE
   * @nullable
   */
  fdeExpireDate?: string | null;
  /** @nullable */
  fpExpireDate?: string | null;
  /** @nullable */
  hamExpireDate?: string | null;
  /** @nullable */
  odsExpireDate?: string | null;
  /**
   * FE
   * @nullable
   */
  pfaExpireDate?: string | null;
}
