/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface Advertise {
  /** 显示顺序 */
  dispNo?: number;
  /** 编辑者 */
  editID?: number;
  /**
   * 企业编号
   * @nullable
   */
  entGid?: number | null;
  /**
   * 图片链接
   * @nullable
   */
  imageName?: string | null;
  /** 是否显示？ */
  isShow?: boolean;
  /** 允许匿名查看 */
  isVisitor?: boolean;
  /** 修改日期 */
  modifyDate?: string;
  /** 编号 */
  sNo?: number;
  /**
   * 标题
   * @nullable
   */
  subject?: string | null;
  /**
   * 标题链接
   * @nullable
   */
  url?: string | null;
}
