/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { Module2 } from './module2';
import type { SubModule4 } from './subModule4';

export interface AfterTaxIncome {
  /** @nullable */
  detail?: Module2[] | null;
  total?: SubModule4;
}
