/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 计算2 - 设置3 - 退休後可領回之生存年金
 */
export interface AfterRetirement {
  /**
   * 年金金額
   * @minLength 1
   */
  annuity: string;
  /**
   * 名稱
   * @nullable
   */
  annuityName?: string | null;
  /** [显示] 到退休後總金額 */
  benefitAmount: number;
  /**
   * 到期年
   * @minLength 1
   */
  endYear: string;
  /**
   * 給付起始年
   * @minLength 1
   */
  startYear: string;
}
