/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 计算2 - 设置1 - 已備定期定額投資
 */
export interface AlreadyPrepared {
  /** [显示] 到退休時總金額 */
  benefitAmount: number;
  /**
   * 到期年
   * @minLength 1
   */
  endYear: string;
  /** 計入退休 */
  isPutInRetire: boolean;
  /**
   * 每月金額
   * @minLength 1
   */
  putInValue: string;
  /**
   * 再投資報酬率
   * @minLength 1
   */
  refillRate: string;
  /**
   * 名稱
   * @nullable
   */
  regularName?: string | null;
  /**
   * 預定報酬率
   * @minLength 1
   */
  setRate: string;
  /**
   * 投資起始年
   * @minLength 1
   */
  startYear: string;
}
