/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 年金/投聯險 使用者自定的給付及增值率設定
 */
export interface AnnuitySettingBase {
  /** 年金開始給付年齡 */
  annuityAge?: number;
  /** 年金給付金額 */
  annuityValue?: number;
  /** 增值率 */
  antyIRate?: number;
  /** 年金保證給付次數 */
  antyPayTimes?: number;
  /** 繳費年期 */
  antyPayYear?: number;
  /** 保障年齡 */
  antyProtectAge?: number;
}
