/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 年度保單分析
 */
export interface AnnualPolicy {
  /** @nullable */
  itemCount?: number[] | null;
  /** @nullable */
  premiums?: number[] | null;
  /** @nullable */
  year?: number[] | null;
}
