/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { IComp } from './iComp';
import type { EnterpriseSimple } from './enterpriseSimple';
import type { Role } from './role';
import type { SysPhrase } from './sysPhrase';

/**
 * 基础数据(简化版)
 */
export interface BaseDataSimple {
  /**
   * 保險公司 (insType: 類型 'A':全部, '0':壽險, '1':產險)
   * @nullable
   */
  company?: IComp[] | null;
  /**
   * 企业
   * @nullable
   */
  enterprises?: EnterpriseSimple[] | null;
  /**
   * 角色
   * @nullable
   */
  roles?: Role[] | null;
  /**
   * 片语(系统)
   * @nullable
   */
  sysPhrases?: SysPhrase[] | null;
}
