/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 计算2 - 设置2 - 退休前可領回之儲蓄險
 */
export interface BeforeRetirement {
  /** [显示] 估算累計滿期金(解約金) */
  benefitAmount: number;
  /**
   * 滿期金(解約金)
   * @minLength 1
   */
  edAmount: string;
  /**
   * 到期年
   * @minLength 1
   */
  expiredYear: string;
  /**
   * 保單說明
   * @nullable
   */
  insrName?: string | null;
  /**
   * 再投資報酬率
   * @minLength 1
   */
  refillRate: string;
}
