/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface BindingParam {
  /**
   * 顯示名稱
   * @nullable
   */
  displayName?: string | null;
  /**
   * 第3方鍵值
   * @nullable
   */
  openId?: string | null;
  /**
   * 提供者(EX:LINE)
   * @nullable
   */
  provider?: string | null;
}
