/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface BindingInfo {
  /**
   * 帳號
   * @nullable
   */
  accountID?: string | null;
  /** @nullable */
  displayName?: string | null;
  /**
   * 提供者(EX:LINE)
   * @nullable
   */
  loginProvider?: string | null;
  /**
   * 第3方鍵值
   * @nullable
   */
  providerKey?: string | null;
  /**
   * 使用者姓名
   * @nullable
   */
  userName?: string | null;
}
