/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 時事分享
 */
export interface Blog {
  /**
   * 類別
   * @nullable
   */
  catagoryId?: string | null;
  /**
   * ?
   * @nullable
   */
  content?: string | null;
  editID?: number;
  /**
   * ?
   * @minLength 0
   * @maxLength 50
   * @nullable
   */
  fileName?: string | null;
  /**
   * ?
   * @nullable
   */
  goodIt?: number | null;
  /**
   * ?
   * @nullable
   */
  isReference?: boolean | null;
  /**
   * ?
   * @minLength 0
   * @maxLength 16
   * @nullable
   */
  mime?: string | null;
  modifyDate?: string;
  /**
   * ?
   * @nullable
   */
  pic?: string | null;
  sNo?: number;
  /**
   * 來源
   * @minLength 0
   * @maxLength 50
   * @nullable
   */
  source?: string | null;
  /**
   * 標題
   * @minLength 0
   * @maxLength 50
   * @nullable
   */
  subject?: string | null;
  /**
   * 網址
   * @minLength 0
   * @maxLength 511
   * @nullable
   */
  url?: string | null;
}
