/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 時事分享查询
 */
export interface BlogPackageQueryModel {
  /**
   * 類別
   * @nullable
   */
  catagoryId?: string | null;
  /** @nullable */
  editId?: number | null;
  /** 页码 */
  pageNum?: number;
  /** @nullable */
  pageSize?: number | null;
  /**
   * 來源
   * @nullable
   */
  source?: string | null;
  /**
   * 標題
   * @nullable
   */
  subject?: string | null;
}
