/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { BlogPageDataPlusData } from './blogPageDataPlusData';
import type { BlogDataWithPageInfo } from './blogDataWithPageInfo';

export interface BlogPageDataPlus {
  /** @nullable */
  data?: BlogPageDataPlusData;
  pageData?: BlogDataWithPageInfo;
}
