/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface BodyContentStatistics {
  /** 目前(年)支出 */
  nowPay?: number;
  /** 退休首年(年)支出(複利計算-[基本]) */
  retireFirstBasicsPay?: number;
  /** 退休首年(年)支出(複利計算-[基本+品質]) */
  retireFirstPay?: number;
  /** 退休首年(年)支出(複利計算-[品質]) */
  retireFirstQualityPay?: number;
  /** 退休首年(年)支出 */
  retirePay?: number;
}
