/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { BodyContent } from './bodyContent';

export interface Body {
  /** @nullable */
  content?: BodyContent[] | null;
  /**
   * 類別(食, 衣, 住, 行, 育, 樂, 其他, 生活總支出)
   * @nullable
   */
  type?: string | null;
}
