/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface BodyContent {
  /** 目前(月)支出 */
  nowPay?: number;
  /** 品質退休生活 */
  qualityPay?: boolean;
  /** 退休首年(月)支出(複利計算) */
  retireFirstPay?: number;
  /** 退休首年(月)支出 */
  retirePay?: number;
  /**
   * 科目
   * @nullable
   */
  subject?: string | null;
}
