/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface Bulliten {
  /**
   * @minLength 0
   * @maxLength 50
   * @nullable
   */
  appendFileName?: string | null;
  appendGid?: number;
  /**
   * @minLength 0
   * @maxLength 200
   * @nullable
   */
  content?: string | null;
  editID?: number;
  endDate?: string;
  enterpriseGID?: number;
  gid?: number;
  /**
   * @minLength 0
   * @maxLength 8
   */
  iType: string;
  /**
   * @minLength 0
   * @maxLength 200
   * @nullable
   */
  linkURL?: string | null;
  modifyDate?: string;
  readLog?: boolean;
  scope?: number;
  /**
   * @minLength 0
   * @maxLength 50
   * @nullable
   */
  source?: string | null;
  startDate?: string;
  targetID?: number;
  /**
   * @minLength 0
   * @maxLength 50
   */
  topic: string;
}
