/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 公告查询条件
 */
export interface BullitenQueryModel {
  /**
   * 默认：未下架
   * @nullable
   */
  endDate?: string | null;
  /** @nullable */
  enterpriseGID?: number | null;
  /** 排序順序。默認：true */
  isDesc?: boolean;
  /** @nullable */
  iType?: string | null;
  /**
   * 排序列。默認：StartDate
   * @nullable
   */
  orderBy?: string | null;
  pageIndex?: number;
  pageSize?: number;
  /** @nullable */
  source?: string | null;
  /**
   * 默认：已上架
   * @nullable
   */
  startDate?: string | null;
  /** @nullable */
  topic?: string | null;
}
