/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { Bulliten } from './bulliten';

export interface BullitenJsonData {
  code?: number;
  data?: Bulliten;
  /** @nullable */
  message?: string | null;
  status?: boolean;
}
