/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { CustomerForSche } from './customerForSche';
import type { FestivalHoliday } from './festivalHoliday';
import type { PolicyForSche } from './policyForSche';
import type { Schedule } from './schedule';

/**
 * 行事历数据
 */
export interface CalendarData {
  /**
   * 生日
   * @nullable
   */
  birthday?: CustomerForSche[] | null;
  /**
   * 假日
   * @nullable
   */
  holiday?: FestivalHoliday[] | null;
  /**
   * 应缴保费
   * @nullable
   */
  policy?: PolicyForSche[] | null;
  /**
   * 行程
   * @nullable
   */
  scheduleDay?: Schedule[] | null;
}
