/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { CalendarData } from './calendarData';

export interface CalendarDataJsonData {
  code?: number;
  data?: CalendarData;
  /** @nullable */
  message?: string | null;
  status?: boolean;
}
