/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface CannedNewsD {
  /** @nullable */
  id?: number | null;
  /**
   * 內容
   * @minLength 0
   * @maxLength 160
   */
  newsletter: string;
}
