/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface CardData {
  /**
   * 持卡人姓名
   * @nullable
   */
  cardHolder?: string | null;
  /**
   * 卡號
   * @nullable
   */
  cardNo?: string | null;
  /**
   * 末三碼
   * @nullable
   */
  cvV2?: string | null;
  /**
   * 到期日 月 + 年
   * @nullable
   */
  expiryDate?: string | null;
}
