/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 车辆信息
 */
export interface CarInfoDto {
  /**
   * 排氣量
   * @minLength 0
   * @maxLength 12
   * @nullable
   */
  cc?: string | null;
  /**
   * 車輛種類
   * @minLength 0
   * @maxLength 10
   * @nullable
   */
  cType?: string | null;
  /**
   * 引擎號碼
   * @minLength 0
   * @maxLength 18
   * @nullable
   */
  engineNo?: string | null;
  /**
   * 廠牌
   * @minLength 0
   * @maxLength 16
   * @nullable
   */
  factory?: string | null;
  /**
   * 牌照號碼
   * @minLength 0
   * @maxLength 12
   * @nullable
   */
  licensePlate?: string | null;
  /**
   * 車型
   * @minLength 0
   * @maxLength 16
   * @nullable
   */
  model?: string | null;
}
