/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { CashValue } from './cashValue';

export interface CashValueListJsonData {
  code?: number;
  /** @nullable */
  data?: CashValue[] | null;
  /** @nullable */
  message?: string | null;
  status?: boolean;
}
