/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 解约金
 */
export interface CashValue {
  /**
   * 保险年龄
   * @nullable
   */
  insureAge?: number | null;
  /**
   * 险种代號
   * @minLength 0
   * @maxLength 10
   * @nullable
   */
  mark?: string | null;
  policyGuid?: string;
  /** @nullable */
  policyItemGuid?: string | null;
  /**
   * 投保日期
   * @nullable
   */
  sDate?: string | null;
  /**
   * 序號
   * @nullable
   */
  sno?: number | null;
  /** 被保人Id */
  targetGuid?: string;
  /** @nullable */
  year1?: number | null;
  /** @nullable */
  year10?: number | null;
  /** @nullable */
  year100?: number | null;
  /** @nullable */
  year101?: number | null;
  /** @nullable */
  year102?: number | null;
  /** @nullable */
  year103?: number | null;
  /** @nullable */
  year104?: number | null;
  /** @nullable */
  year105?: number | null;
  /** @nullable */
  year106?: number | null;
  /** @nullable */
  year107?: number | null;
  /** @nullable */
  year108?: number | null;
  /** @nullable */
  year109?: number | null;
  /** @nullable */
  year11?: number | null;
  /** @nullable */
  year110?: number | null;
  /** @nullable */
  year111?: number | null;
  /** @nullable */
  year12?: number | null;
  /** @nullable */
  year13?: number | null;
  /** @nullable */
  year14?: number | null;
  /** @nullable */
  year15?: number | null;
  /** @nullable */
  year16?: number | null;
  /** @nullable */
  year17?: number | null;
  /** @nullable */
  year18?: number | null;
  /** @nullable */
  year19?: number | null;
  /** @nullable */
  year2?: number | null;
  /** @nullable */
  year20?: number | null;
  /** @nullable */
  year21?: number | null;
  /** @nullable */
  year22?: number | null;
  /** @nullable */
  year23?: number | null;
  /** @nullable */
  year24?: number | null;
  /** @nullable */
  year25?: number | null;
  /** @nullable */
  year26?: number | null;
  /** @nullable */
  year27?: number | null;
  /** @nullable */
  year28?: number | null;
  /** @nullable */
  year29?: number | null;
  /** @nullable */
  year3?: number | null;
  /** @nullable */
  year30?: number | null;
  /** @nullable */
  year31?: number | null;
  /** @nullable */
  year32?: number | null;
  /** @nullable */
  year33?: number | null;
  /** @nullable */
  year34?: number | null;
  /** @nullable */
  year35?: number | null;
  /** @nullable */
  year36?: number | null;
  /** @nullable */
  year37?: number | null;
  /** @nullable */
  year38?: number | null;
  /** @nullable */
  year39?: number | null;
  /** @nullable */
  year4?: number | null;
  /** @nullable */
  year40?: number | null;
  /** @nullable */
  year41?: number | null;
  /** @nullable */
  year42?: number | null;
  /** @nullable */
  year43?: number | null;
  /** @nullable */
  year44?: number | null;
  /** @nullable */
  year45?: number | null;
  /** @nullable */
  year46?: number | null;
  /** @nullable */
  year47?: number | null;
  /** @nullable */
  year48?: number | null;
  /** @nullable */
  year49?: number | null;
  /** @nullable */
  year5?: number | null;
  /** @nullable */
  year50?: number | null;
  /** @nullable */
  year51?: number | null;
  /** @nullable */
  year52?: number | null;
  /** @nullable */
  year53?: number | null;
  /** @nullable */
  year54?: number | null;
  /** @nullable */
  year55?: number | null;
  /** @nullable */
  year56?: number | null;
  /** @nullable */
  year57?: number | null;
  /** @nullable */
  year58?: number | null;
  /** @nullable */
  year59?: number | null;
  /** @nullable */
  year6?: number | null;
  /** @nullable */
  year60?: number | null;
  /** @nullable */
  year61?: number | null;
  /** @nullable */
  year62?: number | null;
  /** @nullable */
  year63?: number | null;
  /** @nullable */
  year64?: number | null;
  /** @nullable */
  year65?: number | null;
  /** @nullable */
  year66?: number | null;
  /** @nullable */
  year67?: number | null;
  /** @nullable */
  year68?: number | null;
  /** @nullable */
  year69?: number | null;
  /** @nullable */
  year7?: number | null;
  /** @nullable */
  year70?: number | null;
  /** @nullable */
  year71?: number | null;
  /** @nullable */
  year72?: number | null;
  /** @nullable */
  year73?: number | null;
  /** @nullable */
  year74?: number | null;
  /** @nullable */
  year75?: number | null;
  /** @nullable */
  year76?: number | null;
  /** @nullable */
  year77?: number | null;
  /** @nullable */
  year78?: number | null;
  /** @nullable */
  year79?: number | null;
  /** @nullable */
  year8?: number | null;
  /** @nullable */
  year80?: number | null;
  /** @nullable */
  year81?: number | null;
  /** @nullable */
  year82?: number | null;
  /** @nullable */
  year83?: number | null;
  /** @nullable */
  year84?: number | null;
  /** @nullable */
  year85?: number | null;
  /** @nullable */
  year86?: number | null;
  /** @nullable */
  year87?: number | null;
  /** @nullable */
  year88?: number | null;
  /** @nullable */
  year89?: number | null;
  /** @nullable */
  year9?: number | null;
  /** @nullable */
  year90?: number | null;
  /** @nullable */
  year91?: number | null;
  /** @nullable */
  year92?: number | null;
  /** @nullable */
  year93?: number | null;
  /** @nullable */
  year94?: number | null;
  /** @nullable */
  year95?: number | null;
  /** @nullable */
  year96?: number | null;
  /** @nullable */
  year97?: number | null;
  /** @nullable */
  year98?: number | null;
  /** @nullable */
  year99?: number | null;
}
