/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 年度解约金
 */
export interface CashValues {
  /**
   * 金额
   * @nullable
   */
  cash?: number | null;
  /**
   * 年份
   * @nullable
   */
  policyYear?: number | null;
}
