/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 图表-年龄
 */
export interface ChartAge {
  /** @nullable */
  female?: number[] | null;
  /** @nullable */
  male?: number[] | null;
  /** @nullable */
  title?: string | null;
}
