/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 图表-性别
 */
export interface ChartSex {
  female?: number;
  male?: number;
  other?: number;
  /** @nullable */
  title?: string | null;
}
