/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface CodeArea {
  /** @nullable */
  area?: string | null;
  /** @nullable */
  code?: string | null;
}
