/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 子模块(通用)
 */
export interface CommonSubModule {
  /** 投入資金 */
  cost?: number;
  /** 遺產稅課稅金額 */
  inheritanceTax?: number;
  /** 目前市值 */
  marketPrice?: number;
  /**
   * 種類
   * @nullable
   */
  subType?: string | null;
}
