/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { SimpleTxtProfit } from './simpleTxtProfit';

/**
 * 險種比較 文字利益結果集合
 */
export interface CompareTxtProfitCollect {
  /** @nullable */
  profitLine?: SimpleTxtProfit[] | null;
}
