/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { AddValueExpireDate } from './addValueExpireDate';

export interface CompanyExpireDate {
  expireDate?: AddValueExpireDate;
  gid?: number;
  /** @nullable */
  shortName?: string | null;
}
