/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 聯繫紀錄查询
 */
export interface ContactRecordPackageQueryModel {
  /**
   * 標題
   * @nullable
   */
  caption?: string | null;
  /**
   * 備註
   * @nullable
   */
  content?: string | null;
  /**
   * 客戶姓名
   * @nullable
   */
  cstm?: string | null;
  /**
   * 階段
   * @nullable
   */
  finish?: string | null;
  /** 页码 */
  pageNum?: number;
  /**
   * 狀態
   * @nullable
   */
  progress?: string | null;
  /**
   * 開始日期(起)
   * @nullable
   */
  startTimeBegin?: string | null;
  /**
   * 開始日期(訖)
   * @nullable
   */
  startTimeEnd?: string | null;
  /**
   * 類型(0:訓練, 1:銷售, 2:增員, 3:服務, 6:其他)
   * @nullable
   */
  type?: number | null;
}
