/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface CreditCardCodeData {
  /**
   * 信用卡代碼
   * @nullable
   */
  last4Cardno?: string | null;
  /**
   * 信用卡代碼
   * @nullable
   */
  paymentToken?: string | null;
  /**
   * 代碼有效期限
   * @nullable
   */
  tokenExpireDate?: string | null;
  /**
   * 代碼認證資料
   * @nullable
   */
  verificationCode?: string | null;
}
