/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface CreditTokenSendCardDataType {
  /** @nullable */
  cardHolder?: string | null;
  /** @nullable */
  cardNo?: string | null;
  /** @nullable */
  cvV2?: string | null;
  /** @nullable */
  expiryDate?: string | null;
  /** @nullable */
  paymentToken?: string | null;
  /** @nullable */
  timestamp?: string | null;
  /** @nullable */
  tokenExpiryDate?: string | null;
  /** @nullable */
  type?: string | null;
  /** @nullable */
  userID?: string | null;
  /** @nullable */
  verificationCode?: string | null;
}
