/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 保單健診查询
 */
export interface CstmHcPackageQueryModel {
  /** 保单健诊(false:个人, true:家庭) */
  family: boolean;
  /**
   * 證件號碼
   * @nullable
   */
  identityNo?: string | null;
  /**
   * 姓名
   * @nullable
   */
  name?: string | null;
  /** 页码 */
  pageNum: number;
}
