/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface CstmPackageQueryModelPlus {
  /**
   * 生日月份
   * @nullable
   */
  birthdayMonth?: number | null;
  /**
   * 常用地址
   * @nullable
   */
  contact?: string | null;
  /**
   * 发送内容
   * @nullable
   */
  content?: string | null;
  /**
   * 客戶編號
   * @nullable
   */
  cstmNo?: string | null;
  /**
   * 发送日期
   * @nullable
   */
  date?: string | null;
  /**
   * 暱稱
   * @nullable
   */
  english?: string | null;
  /**
   * 身分證字號
   * @nullable
   */
  id?: string | null;
  /**
   * 手機號碼
   * @nullable
   */
  mobile?: string | null;
  /**
   * 姓名
   * @nullable
   */
  name?: string | null;
  /** 页码 */
  pageNum?: number;
  /**
   * 是否分页
   * @nullable
   */
  pagination?: boolean | null;
  /**
   * 发送时间 (格式: "09:30")
   * @nullable
   */
  timeSpan?: string | null;
  /** 发送类型 (0:即時發送, 1:預約發送, 2:生日發送) */
  type?: number;
}
