/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 客戶服務
 */
export interface CstmService {
  /**
   * 啟用日期
   * @nullable
   */
  actDate?: string | null;
  /**
   * 卡片
   * @nullable
   */
  card?: boolean | null;
  /**
   * 內容
   * @minLength 0
   * @maxLength 64
   * @nullable
   */
  content?: string | null;
  /**
   * 客戶Id
   * @nullable
   */
  cstmGuid?: string | null;
  /**
   * 傳單
   * @nullable
   */
  dm?: boolean | null;
  /**
   * 禮物
   * @nullable
   */
  gift?: boolean | null;
  guid?: string;
  /**
   * 信件
   * @nullable
   */
  letter?: boolean | null;
  /**
   * 修改日期
   * @nullable
   */
  modifyDate?: string | null;
  /**
   * 建議書
   * @nullable
   */
  pp?: boolean | null;
  /**
   * 結果
   * @minLength 0
   * @maxLength 10
   * @nullable
   */
  result?: string | null;
  /**
   * 類型
   * @minLength 0
   * @maxLength 10
   * @nullable
   */
  type?: string | null;
}
