/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 客户家属查询
 */
export interface CstmFamilyPackageQueryModel {
  /**
   * 当前客户Id
   * @nullable
   */
  guid?: string | null;
  /**
   * 姓名
   * @nullable
   */
  name?: string | null;
  /** 页码 */
  pageNum: number;
}
