/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { CstmService } from './cstmService';
import type { VFamilyLink2 } from './vFamilyLink2';
import type { LinkLine } from './linkLine';
import type { OpenCustomer } from './openCustomer';
import type { Policy } from './policy';
import type { Schedule } from './schedule';
import type { Tag } from './tag';

/**
 * 客户
 */
export interface Customer {
  /**
   * 客戶等級: 原因
   * @minLength 0
   * @maxLength 50
   * @nullable
   */
  actstr?: string | null;
  /**
   * 保险年龄
   * @nullable
   */
  readonly age?: number | null;
  /**
   * 銷售活動建議
   * @nullable
   */
  aiSuggest?: string | null;
  /**
   * 淨資產
   * @minLength 0
   * @maxLength 12
   * @nullable
   */
  assert?: string | null;
  /**
   * 生日
   * @nullable
   */
  birthday?: string | null;
  /**
   * 出生地
   * @minLength 0
   * @maxLength 10
   * @nullable
   */
  birthPlace?: string | null;
  /**
   * 血型
   * @minLength 0
   * @maxLength 2
   * @nullable
   */
  bool?: string | null;
  /**
   * 購買保單
   * @minLength 0
   * @maxLength 6
   * @nullable
   */
  buy?: string | null;
  /** 職業等級 */
  cLevel?: number;
  /**
   * 常用地址(名)
   * @minLength 0
   * @maxLength 12
   * @nullable
   */
  commaddr?: string | null;
  /**
   * 常用郵件(名)
   * @minLength 0
   * @maxLength 12
   * @nullable
   */
  commMail?: string | null;
  /**
   * 常用電話(名)
   * @minLength 0
   * @maxLength 12
   * @nullable
   */
  commtel?: string | null;
  /**
   * 服務單位
   * @minLength 0
   * @maxLength 32
   * @nullable
   */
  company?: string | null;
  /**
   * 初登日
   * @nullable
   */
  conDate?: string | null;
  /**
   * 星座
   * @minLength 0
   * @maxLength 12
   * @nullable
   */
  constellation?: string | null;
  /**
   * 常用地址(值)
   * @minLength 0
   * @maxLength 300
   * @nullable
   */
  contact?: string | null;
  /**
   * 客戶編號
   * @minLength 0
   * @maxLength 10
   * @nullable
   */
  cstmNo?: string | null;
  /**
   * 客户服务
   * @nullable
   */
  cstmServices?: CstmService[] | null;
  /**
   * 客戶來源
   * @minLength 0
   * @maxLength 6
   * @nullable
   */
  cstmsur?: string | null;
  /**
   * 部門
   * @minLength 0
   * @maxLength 10
   * @nullable
   */
  department?: string | null;
  /** 編輯者 */
  editID?: number;
  /**
   * 常用郵件(值)
   * @minLength 0
   * @maxLength 40
   * @nullable
   */
  eMail?: string | null;
  /**
   * 暱稱
   * @minLength 0
   * @maxLength 20
   * @nullable
   */
  english?: string | null;
  /**
   * 家庭关系
   * @nullable
   */
  familyLink2?: VFamilyLink2[] | null;
  /**
   * 家庭關係
   * @minLength 0
   * @maxLength 8
   * @nullable
   */
  fmlyRLT?: string | null;
  /**
   * 客戶等級: 判定等級
   * @minLength 0
   * @maxLength 10
   * @nullable
   */
  grade?: string | null;
  guid?: string;
  /**
   * 嗜好標籤
   * @minLength 0
   * @maxLength 48
   * @nullable
   */
  hbtList?: string | null;
  /**
   * 常用電話(值)
   * @minLength 0
   * @maxLength 24
   * @nullable
   */
  hPhone?: string | null;
  /**
   * 證件號碼
   * @minLength 0
   * @maxLength 20
   * @nullable
   */
  id?: string | null;
  /**
   * 證件类型
   * @minLength 0
   * @maxLength 8
   * @nullable
   */
  idType?: string | null;
  /**
   * 介紹人
   * @minLength 0
   * @maxLength 10
   * @nullable
   */
  introder?: string | null;
  /** 雲端_主聯絡人 */
  isHost?: boolean;
  /**
   * 接觸分類
   * @nullable
   */
  kndiff?: number | null;
  /**
   * 接觸等級
   * @nullable
   */
  knLevel?: number | null;
  /**
   * 接觸方式
   * @nullable
   */
  knMeet?: number | null;
  /**
   * 接觸年
   * @nullable
   */
  knYear?: number | null;
  /**
   * 片语
   * @nullable
   */
  linkLines?: LinkLine[] | null;
  /**
   * 郵件稱謂
   * @minLength 0
   * @maxLength 10
   * @nullable
   */
  mailCall?: string | null;
  /**
   * 打印"郵寄標籤"地址
   * @nullable
   */
  mailingLabelAddress?: string | null;
  /**
   * 郵件寄送標籤
   * @minLength 0
   * @maxLength 48
   * @nullable
   */
  maiList?: string | null;
  /**
   * 婚姻狀況
   * @minLength 0
   * @maxLength 10
   * @nullable
   */
  marry?: string | null;
  /**
   * 增員來源
   * @minLength 0
   * @maxLength 6
   * @nullable
   */
  mbrsur?: string | null;
  /**
   * 增員對象
   * @minLength 0
   * @maxLength 6
   * @nullable
   */
  member?: string | null;
  /**
   * 手機號碼
   * @minLength 0
   * @maxLength 16
   * @nullable
   */
  mobile?: string | null;
  /** @nullable */
  modifyDate?: string | null;
  /**
   * 姓名
   * @minLength 0
   * @maxLength 50
   */
  name: string;
  /**
   * 客戶等級: 類型
   * @nullable
   */
  nameType?: number | null;
  openCustomer?: OpenCustomer;
  /**
   * 客戶等級: 進行階段
   * @minLength 0
   * @maxLength 50
   * @nullable
   */
  phase?: string | null;
  /**
   * 大頭照
   * @nullable
   */
  photo?: string | null;
  /**
   * 保单
   * @nullable
   */
  policies?: Policy[] | null;
  /**
   * 是否列印
   * @nullable
   */
  printIt?: boolean | null;
  /**
   * 備註
   * @nullable
   */
  remark?: string | null;
  /**
   * 關係標籤
   * @minLength 0
   * @maxLength 48
   * @nullable
   */
  rltList?: string | null;
  /**
   * 客戶等級: 行銷對策
   * @nullable
   */
  rsnsel?: number | null;
  /**
   * 年收入
   * @minLength 0
   * @maxLength 10
   * @nullable
   */
  salary?: string | null;
  /**
   * 日历
   * @nullable
   */
  schedules?: Schedule[] | null;
  /**
   * 自訂一
   * @minLength 0
   * @maxLength 10
   * @nullable
   */
  self1?: string | null;
  /**
   * 自訂二
   * @minLength 0
   * @maxLength 10
   * @nullable
   */
  self2?: string | null;
  /**
   * 自訂日期
   * @nullable
   */
  self3?: string | null;
  /**
   * 建立日期
   * @nullable
   */
  setDate?: string | null;
  /**
   * 業務員ID
   * @minLength 0
   * @maxLength 10
   * @nullable
   */
  setID?: string | null;
  /**
   * 性別
   * @minLength 0
   * @maxLength 2
   * @nullable
   */
  sex?: string | null;
  /**
   * 标签
   * @nullable
   */
  tags?: Tag[] | null;
  /**
   * 職稱
   * @minLength 0
   * @maxLength 10
   * @nullable
   */
  title?: string | null;
}
