/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 明细
 */
export interface CustomGroupItem {
  /**
   * 保額
   * @nullable
   */
  amount?: string | null;
  /**
   * 保險公司代碼
   * @nullable
   */
  companyNo?: string | null;
  /**
   * 險種中文名
   * @nullable
   */
  insName?: string | null;
  /**
   * 險種代號
   * @nullable
   */
  mark?: string | null;
  /**
   * 年期
   * @nullable
   */
  year?: string | null;
}
