/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface CustomerPrint {
  /**
   * 生日月份
   * @nullable
   */
  birthdayMonth?: number | null;
  /**
   * 常用地址
   * @nullable
   */
  contact?: string | null;
  /**
   * 客戶編號
   * @nullable
   */
  cstmNo?: string | null;
  /** 0:簡易資料, 2:詳細資料, 3:郵寄標籤 */
  customerInfoType: number;
  /**
   * 暱稱
   * @nullable
   */
  english?: string | null;
  /**
   * 身分證字號
   * @nullable
   */
  id?: string | null;
  /**
   * 標籤格式 0:2*7 , 1:3*7
   * @nullable
   */
  is27?: boolean | null;
  /**
   * 手機號碼
   * @nullable
   */
  mobile?: string | null;
  /**
   * 姓名
   * @nullable
   */
  name?: string | null;
  /** 页码 */
  pageNum?: number;
  /**
   * 是否分页
   * @nullable
   */
  pagination?: boolean | null;
  /**
   * 寄件人
   * @nullable
   */
  printSender?: boolean | null;
  /**
   * 啟封詞
   * @nullable
   */
  words?: string | null;
}
