/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 客户标签
 */
export interface CustomerTagDto {
  /** 客户Id */
  cstmId: string;
  /** 标签Id */
  tagId: number[];
}
