/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { CustomGroupPlus } from './customGroupPlus';

export interface CustomGroupPlusListJsonData {
  code?: number;
  /** @nullable */
  data?: CustomGroupPlus[] | null;
  /** @nullable */
  message?: string | null;
  status?: boolean;
}
