/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { ChartAge } from './chartAge';
import type { ChartSex } from './chartSex';

/**
 * 名单分析
 */
export interface CustomerAnalysis {
  chartAge?: ChartAge;
  chartSex?: ChartSex;
}
