/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 客戶保障筛选條件
 */
export interface CustomerProfitQueryModel {
  /**
   * 结束Accident
   * @nullable
   */
  accidentEnd?: number | null;
  /**
   * 开始Accident(意外保障-意外身故)
   * @nullable
   */
  accidentStart?: number | null;
  /**
   * 结束Cancer
   * @nullable
   */
  cancerEnd?: number | null;
  /**
   * 开始Cancer(癌症醫療-初次罹癌保險金)
   * @nullable
   */
  cancerStart?: number | null;
  /**
   * 结束年龄
   * @nullable
   */
  cstmAgeEnd?: number | null;
  /**
   * 开始年龄
   * @nullable
   */
  cstmAgeStart?: number | null;
  /**
   * 身份证
   * @nullable
   */
  cstmId?: string | null;
  /**
   * 姓名
   * @nullable
   */
  cstmName?: string | null;
  /**
   * 标签----我最关注中使用，合并和删除这个字段
   * @nullable
   */
  cstmTag?: string | null;
  /**
   * 结束DBR
   * @nullable
   */
  dbrEnd?: number | null;
  /**
   * 开始DBR(重疾特傷-重大疾病)
   * @nullable
   */
  dbrStart?: number | null;
  /**
   * 结束DDR
   * @nullable
   */
  ddrEnd?: number | null;
  /**
   * 开始DDR(重疾特傷-重大傷病保險金(健保))
   * @nullable
   */
  ddrStart?: number | null;
  /**
   * 结束DSL
   * @nullable
   */
  dslEnd?: number | null;
  /**
   * 开始DSL--失能1-11保险金
   * @nullable
   */
  dslStart?: number | null;
  /**
   * 结束HI
   * @nullable
   */
  hiEnd?: number | null;
  /**
   * 开始HI(醫療保障-定額給付住院醫療(每日))
   * @nullable
   */
  hiStart?: number | null;
  /**
   * 结束HS
   * @nullable
   */
  hsEnd?: number | null;
  /**
   * 开始HS(醫療保障-實支實付住院醫療(每次))
   * @nullable
   */
  hsStart?: number | null;
  isDesc?: boolean;
  /**
   * 结束LIFE
   * @nullable
   */
  lifeEnd?: number | null;
  /**
   * 结束LifeGift
   * @nullable
   */
  lifeGiftEnd?: number | null;
  /**
   * 开始LifeGift
   * @nullable
   */
  lifeGiftStart?: number | null;
  /**
   * 开始LIFE(壽險保障-目前保障)
   * @nullable
   */
  lifeStart?: number | null;
  /**
   * 结束LoseMonth
   * @nullable
   */
  loseMonthEnd?: number | null;
  /**
   * 开始LoseMonth
   * @nullable
   */
  loseMonthStart?: number | null;
  /**
   * 结束开始LoseYear
   * @nullable
   */
  loseYearEnd?: number | null;
  /**
   * 开始LoseYear-----1-6級失能生活扶助(年化給付)
   * @nullable
   */
  loseYearStart?: number | null;
  /**
   * 结束LTC
   * @nullable
   */
  ltcEnd?: number | null;
  /**
   * 开始LTC---長期看護保險金(年化給付)
   * @nullable
   */
  ltcStart?: number | null;
  pageIndex?: number;
  pageSize?: number;
  /**
   * 结束SDR
   * @nullable
   */
  sdrEnd?: number | null;
  /**
   * 开始SDR(重疾特傷-特定傷病)
   * @nullable
   */
  sdrStart?: number | null;
  /**
   * 性別
   * @nullable
   */
  sex?: string | null;
  /** @nullable */
  sortField?: string | null;
  /** 表格显示方式 */
  tableStyle?: number;
  /** (后端设定)當前使用者 */
  userId?: number;
}
