/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { Customer } from './customer';
import type { PagingInfo } from './pagingInfo';

export interface CustomerDataWithPageInfo {
  /** @nullable */
  datas?: Customer[] | null;
  /** @nullable */
  message?: string | null;
  pageInfo?: PagingInfo;
}
