/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { TagId } from './tagId';

export interface CustomerDto {
  /**
   * 客戶等級: 原因
   * @minLength 0
   * @maxLength 50
   * @nullable
   */
  actstr?: string | null;
  /**
   * 淨資產
   * @minLength 0
   * @maxLength 12
   * @nullable
   */
  assert?: string | null;
  /**
   * 生日
   * @nullable
   */
  birthday?: string | null;
  /**
   * 血型
   * @minLength 0
   * @maxLength 2
   * @nullable
   */
  bool?: string | null;
  /** 職業等級 */
  cLevel: number;
  /**
   * 常用地址(名)
   * @nullable
   */
  readonly commaddr?: string | null;
  /**
   * 服務單位
   * @minLength 0
   * @maxLength 32
   * @nullable
   */
  company?: string | null;
  /**
   * 常用地址(值)
   * @nullable
   */
  readonly contact?: string | null;
  /**
   * 住家地址(段1)
   * @minLength 0
   * @maxLength 50
   * @nullable
   */
  contact1?: string | null;
  /**
   * 住家地址(段2)
   * @minLength 0
   * @maxLength 50
   * @nullable
   */
  contact2?: string | null;
  /**
   * 住家地址(段3)
   * @minLength 0
   * @maxLength 190
   * @nullable
   */
  contact3?: string | null;
  /**
   * 客戶編號
   * @minLength 0
   * @maxLength 10
   * @nullable
   */
  cstmNo?: string | null;
  /**
   * 暱稱
   * @minLength 0
   * @maxLength 20
   * @nullable
   */
  english?: string | null;
  /**
   * 客戶等級: 判定等級 [系统片语:Cstm-grade]
   * @minLength 0
   * @maxLength 10
   * @nullable
   */
  grade?: string | null;
  /** @nullable */
  guid?: string | null;
  /**
   * 證件號碼
   * @minLength 0
   * @maxLength 20
   * @nullable
   */
  id?: string | null;
  /**
   * 證件類別
   * @minLength 0
   * @maxLength 8
   */
  idType: string;
  /**
   * 介紹人
   * @minLength 0
   * @maxLength 10
   * @nullable
   */
  introder?: string | null;
  /**
   * 婚姻狀況
   * @minLength 0
   * @maxLength 10
   * @nullable
   */
  marry?: string | null;
  /**
   * 手機號碼
   * @minLength 0
   * @maxLength 16
   * @nullable
   */
  mobile?: string | null;
  /**
   * 姓名
   * @minLength 0
   * @maxLength 50
   */
  name: string;
  /**
   * 客戶等級: 類型 [系统片语:Cstm-type, 類型+行銷對策+原因 三级联动]
   * @nullable
   */
  nameType?: number | null;
  /**
   * 客戶等級: 進行階段 [系统片语:Cstm-phs]
   * @minLength 0
   * @maxLength 50
   * @nullable
   */
  phase?: string | null;
  /**
   * 備註
   * @nullable
   */
  remark?: string | null;
  /**
   * 客戶等級: 行銷對策
   * @nullable
   */
  rsnsel?: number | null;
  /**
   * 年收入
   * @minLength 0
   * @maxLength 10
   * @nullable
   */
  salary?: string | null;
  /**
   * 性別
   * @minLength 0
   * @maxLength 2
   */
  sex: string;
  /**
   * 标签
   * @nullable
   */
  tags?: TagId[] | null;
  /**
   * 職稱
   * @minLength 0
   * @maxLength 10
   * @nullable
   */
  title?: string | null;
}
