/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { CustomerAnalysis } from './customerAnalysis';

export interface CustomerAnalysisJsonData {
  code?: number;
  data?: CustomerAnalysis;
  /** @nullable */
  message?: string | null;
  status?: boolean;
}
