/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 客戶生日
 */
export interface CustomerForSche {
  /**
   * 今年生日
   * @nullable
   */
  birthday?: string | null;
  guid?: string;
  /**
   * 保险年龄
   * @nullable
   */
  insuranceAge?: number | null;
  /** @nullable */
  name?: string | null;
}
