/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { SubModule2 } from './subModule2';

export interface Debt {
  /** @nullable */
  detail?: SubModule2[] | null;
  /** @nullable */
  subject?: string | null;
}
