/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 遺產稅免稅額、扣除額
 */
export interface Deductions {
  /**
   * 喪葬費
   * @nullable
   */
  funeral?: string | null;
  /**
   * 父母扣除額
   * @nullable
   */
  parents?: string | null;
  /**
   * 直系血親卑親屬扣除額
   * @nullable
   */
  relatives?: string | null;
  /**
   * 配偶扣除額
   * @nullable
   */
  spouse?: string | null;
  /**
   * 免稅額
   * @nullable
   */
  taxExemption?: string | null;
}
