/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export type Direction = typeof Direction[keyof typeof Direction];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Direction = {
  Up: 'Up',
  Down: 'Down',
} as const;
