/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export type DspCalenderType = typeof DspCalenderType[keyof typeof DspCalenderType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DspCalenderType = {
  NUMBER_0: 0,
  NUMBER_1: 1,
} as const;
