/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 各國貨幣對預設貨幣的匯率值
 */
export interface ExchangeRate {
  convertUnit?: number;
  /** @nullable */
  currencyName?: string | null;
  /** @nullable */
  dspName?: string | null;
  /** @nullable */
  modifyDate?: string | null;
}
