/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { ExtendSave } from './extendSave';
import type { PagingInfo } from './pagingInfo';

export interface ExtendSaveDataWithPageInfo {
  /** @nullable */
  datas?: ExtendSave[] | null;
  /** @nullable */
  message?: string | null;
  pageInfo?: PagingInfo;
}
