/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 第三方綁定(輸入帳號密碼)
 */
export interface ExternalBindModel {
  /**
   * 验证码
   * @nullable
   */
  code?: string | null;
  /** @nullable */
  displayName?: string | null;
  /**
   * 用户名
   * @minLength 1
   */
  identityNo: string;
  /** @nullable */
  openId?: string | null;
  /**
   * 密碼
   * @minLength 1
   */
  password: string;
  /** @nullable */
  provider?: string | null;
}
