/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 存档文件 查询
 */
export interface ExtendSavePackageQueryModel {
  /**
   * 檔案名稱
   * @nullable
   */
  fileName?: string | null;
  /**
   * 客户Id
   * @minLength 1
   */
  info: string;
  /** 页码 */
  pageNum?: number;
}
