/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 存檔文件
 */
export interface ExtendSave {
  /** 序號 */
  autoInc?: number;
  /** 編輯者 */
  editID?: number;
  /**
   * 檔案名稱
   * @minLength 0
   * @maxLength 100
   */
  fileName: string;
  /**
   * 客户Id
   * @minLength 0
   * @maxLength 100
   */
  info: string;
  /**
   * 資訊名稱(x)
   * @minLength 0
   * @maxLength 20
   * @nullable
   */
  infoName?: string | null;
  /** 訊息類型(1:客管的客戶存檔文件) */
  iType?: number;
  /** 修改日期 */
  modifyDate?: string;
  /** 檔案大小 */
  size?: number;
}
