/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 险种反馈
 */
export interface Feedback {
  /**
   * 解決說明
   * @nullable
   */
  answer?: string | null;
  /**
   * 公司(x)
   * @minLength 0
   * @maxLength 20
   * @nullable
   */
  company?: string | null;
  createDate?: string;
  /**
   * 邮件(x)
   * @minLength 0
   * @maxLength 40
   */
  eMail: string;
  /**
   * 附件名
   * @nullable
   */
  fileName?: string | null;
  /**
   * 帳號
   * @minLength 0
   * @maxLength 20
   * @nullable
   */
  id?: string | null;
  /**
   * 標籤(x)
   * @minLength 0
   * @maxLength 80
   * @nullable
   */
  keyWord?: string | null;
  /**
   * 提報主項目(x)
   * @minLength 0
   * @maxLength 20
   */
  mainItem: string;
  /**
   * 手機(x)
   * @minLength 1
   */
  mobile: string;
  /** @nullable */
  modifyDate?: string | null;
  /**
   * 姓名(x)
   * @minLength 0
   * @maxLength 20
   */
  name: string;
  /**
   * 問題描述
   * @minLength 0
   * @maxLength 250
   */
  reply: string;
  sNo?: number;
  /**
   * 狀態(0:報案, 1:處理, 2:完成, 3:取消, 4:測試)
   * @nullable
   */
  status?: number | null;
}
