/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 反馈信息查询
 */
export interface FeedbackPackageQueryModel {
  /**
   * 開始日期(訖)
   * @nullable
   */
  createDateEnd?: string | null;
  /**
   * 開始日期(起)
   * @nullable
   */
  createDateStart?: string | null;
  /**
   * 姓名
   * @nullable
   */
  name?: string | null;
  /** 页码 */
  pageNum?: number;
  /**
   * 狀態(0:報案, 1:處理, 2:完成, 3:取消, 4:測試)
   * @nullable
   */
  status?: number | null;
}
