/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 节假日
 */
export interface FestivalHoliday {
  allDay?: boolean;
  /**
   * @minLength 0
   * @maxLength 80
   * @nullable
   */
  caption?: string | null;
  /**
   * @minLength 0
   * @maxLength 350
   * @nullable
   */
  content?: string | null;
  /** @nullable */
  editID?: number | null;
  /** @nullable */
  endTime?: string | null;
  guid?: string;
  /** @nullable */
  modifyDate?: string | null;
  /**
   * @minLength 0
   * @maxLength 20
   * @nullable
   */
  source?: string | null;
  startTime?: string;
  type?: number;
}
