/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { AccountingStatisticsData } from './accountingStatisticsData';
import type { Deductions } from './deductions';

/**
 * 固定数据(財務健診)
 */
export interface FixedFinanceData {
  accountingStatisticsData?: AccountingStatisticsData;
  deductions?: Deductions;
}
