/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 家庭型保單註記, 富邦要求家庭型保單需要再保險公司有紀錄,家庭成員才會有保障,此結構為保險公司記錄
 */
export interface FmlyItem { [key: string]: unknown }
