/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 菜单角色关系
 */
export interface FunctionRoleMapNew {
  entId?: number;
  functionID?: number;
  /**
   * @minLength 0
   * @maxLength 16
   * @nullable
   */
  role?: string | null;
}
