/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { FundVideo } from './fundVideo';
import type { PagingInfo } from './pagingInfo';

export interface FundVideoDataWithPageInfo {
  /** @nullable */
  datas?: FundVideo[] | null;
  /** @nullable */
  message?: string | null;
  pageInfo?: PagingInfo;
}
