/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 基金神探
 */
export interface FundVideo {
  /** @nullable */
  createTime?: string | null;
  guid?: string;
  /**
   * 附件
   * @nullable
   */
  image?: string | null;
  /**
   * 附件名
   * @nullable
   */
  imageName?: string | null;
  /** @nullable */
  modifyTime?: string | null;
  /**
   * 影片名稱
   * @minLength 0
   * @maxLength 50
   * @nullable
   */
  name?: string | null;
  /**
   * 文稿
   * @nullable
   */
  text?: string | null;
  /**
   * 影片網址
   * @nullable
   */
  url?: string | null;
}
