/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 基金神探查詢
 */
export interface FundVideoPackageQueryModel {
  /**
   * 結束日期
   * @nullable
   */
  end?: string | null;
  /**
   * 名稱
   * @nullable
   */
  name?: string | null;
  /** 页码 */
  pageNum: number;
  /**
   * 開始日期
   * @nullable
   */
  start?: string | null;
}
