/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export type GetAuthSaveUserPhraseParams = {
/**
 * 類型(11:通訊錄電話, 12:通訊錄地址, 13:通訊錄郵件)
 */
type?: string;
content?: string;
no?: number;
};
