/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export type GetCstmRecentBirthdayParams = {
/**
 * 默认生日30日内的客户
 */
days?: number;
/**
 * 用户，该参数前端不传，由后端设定
 */
userId?: number;
/**
 * [0, ∞]
 */
pageIndex?: number;
pageSize?: number;
};
