/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export type GetExchangeBrokerDataToGoUPParams = {
/**
 * 企業
 */
enterprise?: string;
/**
 * 開始日
 */
startdate?: string;
/**
 * 結束日
 */
enddate?: string;
};
