/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export type GetFinanceToolBackCastingInvRateParams = {
/**
 * 本金(萬)
 */
amount?: number;
/**
 * 期數(月)
 */
period?: number;
/**
 * 每期還款金額(元)
 */
pay?: number;
};
