/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export type GetFinanceToolHouseLoanParams = {
/**
 * 貸款總額(萬)
 */
amount?: number;
/**
 * 貸款期數(月)
 */
period?: number;
/**
 * 本金寬限期(月)
 */
bufferPeriod?: number;
/**
 * 貸款利率(可以設定最多三段利率 第一年，二及往後)
 */
invRates?: number[];
};
