/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export type GetHomeSlidesParams = {
/**
 * 企业编号，未登录时使用默认企业（1），后端已处理
 */
enterpriseGID?: number;
/**
 * 是否为已登录，后端已处理
 */
isVisitor?: boolean;
/**
 * 是否显示？
 */
isShow?: boolean;
/**
 * 是否仅返回设置了图片的
 */
hasImage?: boolean;
pageIndex?: number;
pageSize?: number;
};
