/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { GroupText } from './groupText';

export type GetHealthCheckGroupTextAll200Three = {[key: string]: GroupText[]};
