/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export type GetHealthCheckGenPersonInsrPackObjParams = {
/**
 * 客户主鍵
 */
cstmId?: string;
/**
 * 自訂項號組合範本鍵值
 */
userGtId?: string;
/**
 * 忽略的保單鍵值,以','分隔
 */
excludes?: string;
saveCheck?: number;
parameter?: string;
};
