/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export type GetPolicySortPolicyParams = {
/**
 * 客户Id
 */
cstmId?: string;
/**
 * 0:保險公司(遞增), 1:保險公司(遞減), 2:投保日期(新到舊), 3:投保日期(舊到新)
 */
type?: number;
};
