/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export type GetPerformanceGetTeamOrMyParams = {
isTeam?: boolean;
/**
 * 有值:倒推1年, null:当前年
 */
day?: string;
};
