/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export type GetPolicyGetCashValueListParams = {
/**
 * 保单Id
 */
policyId?: string;
/**
 * 被保人Id
 */
targetGuid?: string;
};
