/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export type GetPolicyUpdateAddValueNewParams = {
/**
 * 是否为测试阶段
 */
testingPeriod?: boolean;
};
