/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export type GetPolicyGetByInrCmpyAndPolicyIdParams = {
/**
 * 保險公司(名称)
 */
inrCmpy?: string;
/**
 * 保單號碼
 */
policyId?: string;
};
