/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export type GetSysManagerExportHIBInsItemParams = {
/**
 * 壽險:L/產險:P
 */
insType?: string;
/**
 * 民國yyyMMdd
 */
dateFrom?: string;
/**
 * 民國yyyMMdd
 */
dateTo?: string;
};
