/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export type GetSysManagerExportTaidaInsItemParams = {
/**
 * Taida
 */
companyType?: string;
/**
 * 2022092102
 */
date?: string;
};
