/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export type GetScheduleTripReportDisplayParams = {
/**
 * 类型 (1:銷售, 2:增員)
 */
type?: number;
/**
 * 状态 (進行中, 完成, 取消)
 */
finish?: string;
/**
 * true:依時間, false:依數量
 */
byTime?: boolean;
/**
 * 开始时间
 */
startDate?: string;
/**
 * 结束时间
 */
endDate?: string;
descriptionType?: number;
/**
 * true:预览, false:下载
 */
isPreview?: boolean;
};
