/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export type GetScheduleGetParams = {
/**
 * 日期
 */
dt?: string;
/**
 * 是否包含团队数据
 */
containsTeams?: boolean;
};
