/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 保險利益彙總設定
 */
export interface GroupText {
  defaultValue?: boolean;
  groupNo?: number;
  /** @nullable */
  item?: string | null;
  type?: string;
}
