/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 短信群发[最终]
 */
export interface GroupSmsInfoFinal {
  /** 剩餘點數 */
  accountPoint?: number;
  /**
   * 儲值網址
   * @nullable
   */
  amountUrl?: string | null;
  /** 客户数量(全部) */
  customerCount?: number;
  /** 客户数量(登记手机号的) */
  mobileCount?: number;
}
