/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { OCRPolicy } from './oCRPolicy';

export interface GuildPdfResponse {
  id?: number;
  /** @nullable */
  result?: OCRPolicy[] | null;
}
