/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 高資產 Policy.AddValueJson
 */
export interface HighAssets {
  /**
   * 預定利率
   * @nullable
   */
  decRate?: number | null;
  /** Policy主键 */
  guid: string;
  /**
   * 宣告利率
   * @nullable
   */
  preRate?: number | null;
  /**
   * 利率
   * @nullable
   */
  rate?: number | null;
  /**
   * 預計解約年度(废弃不用)
   * @nullable
   */
  readonly termiYear?: number | null;
  /** 高資產类型(1:不歸類, 2:家庭責任保單, 3:退休金管理保單) */
  type: number;
}
