/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 保險公司
 */
export interface IComp {
  /**
   * 保險公司代碼
   * @nullable
   */
  companyNo?: string | null;
  /** 保險公司類型 */
  insType?: number;
  /**
   * 特殊的繳別係數
   * @nullable
   */
  paymentRate?: string | null;
  /**
   * 特例的保費計算模式
   * @nullable
   */
  premiumType?: number | null;
  /** 是否停業 */
  saled?: boolean;
  /**
   * 保險公司中文簡稱
   * @nullable
   */
  shortName?: string | null;
}
