/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 遺產稅免稅額、扣除額
 */
export interface InheritanceTaxExemptionsDeductions {
  /** 喪葬費 */
  funeral?: number;
  /** 父母扣除額 */
  parents?: number;
  /** 父母扣除額(人数) */
  parentsCount?: number;
  /** 直系血親卑親屬扣除額 */
  relatives?: number;
  /** 直系血親卑親屬扣除額(人数) */
  relativesCount?: number;
  /** 配偶扣除額 */
  spouse?: number;
  /** 免稅額 */
  taxExemption?: number;
  /** 扣除額合計 */
  totalDeductions?: number;
}
