/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { FmlyItem } from './fmlyItem';
import type { ITMBase } from './iTMBase';
import type { Ppltype } from './ppltype';
import type { PManBase } from './pManBase';

/**
 * 前端與SERVER交換 建議書物件的JSON定義
 */
export interface InputPPLObj {
  /**
   * 要保人姓名
   * @nullable
   */
  applicant?: string | null;
  /**
   * 收款帳戶訊息 銀行/卡號....
   * @nullable
   */
  bankInfo?: string | null;
  /**
   * 受益人
   * @nullable
   */
  beneficiary?: string | null;
  /**
   * 繳法 信用卡/銀行匯款/收費員....
   * @nullable
   */
  chargeInfo?: string | null;
  /**
   * 保險公司簡稱
   * @nullable
   */
  cmpyName?: string | null;
  /**
   * 保險公司代碼
   * @nullable
   */
  cmpyNo?: string | null;
  /**
   * 解約金
   * @nullable
   */
  csv?: number[] | null;
  /** 保單計算匯率 */
  currencyRate?: number;
  /**
   * 建議書說明字串
   * @nullable
   */
  description?: string | null;
  /**
   * 編輯人員/業務員... 鍵值
   * @nullable
   */
  editID?: string | null;
  /**
   * 加強型個人健診(富邦使用,包含個人健診該員非主被保人的保單)使用的 家庭型商品集合
   * @nullable
   */
  fmlyItems?: FmlyItem[] | null;
  /**
   * 投保險種資料
   * @nullable
   */
  insList?: ITMBase[] | null;
  insType?: Ppltype;
  /** 繳別 0:年繳 1:半年繳.... */
  payment?: number;
  /**
   * 要/被保人 資料
   * @nullable
   */
  pMans?: PManBase[] | null;
  /**
   * DB鍵值 (保單/建議書 datatable primary key)
   * @nullable
   */
  pplGuid?: string | null;
  /**
   * 保單號碼/建議書編號
   * @nullable
   */
  pplNo?: string | null;
  /** 保單/建議書 總保費 */
  premium?: number;
  /**
   * 投保日期
   * @nullable
   */
  setDate?: string | null;
  /**
   * 保單狀態
   * @nullable
   */
  status?: string | null;
}
