/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { InputPPLObj } from './inputPPLObj';

export interface InputPPLObjJsonData {
  code?: number;
  data?: InputPPLObj;
  /** @nullable */
  message?: string | null;
  status?: boolean;
}
