/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 個人保單健診保費匯總方式
 */
export type InsPackPremiumBelongWay = typeof InsPackPremiumBelongWay[keyof typeof InsPackPremiumBelongWay];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InsPackPremiumBelongWay = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;
