/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 保險年齡名單搜尋
 */
export interface InsureAgeQueryModel {
  /** 結束日期 */
  end?: string;
  /**
   * `>=`距离下次保險生日还有几天
   * @nullable
   */
  minAge?: number | null;
  pageIndex?: number;
  pageSize?: number;
  /** 開始日期 */
  start?: string;
  /** (后端设定)當前使用者 */
  userId?: number;
}
