/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface InsuranceCompanyDistributionData {
  /** @nullable */
  company?: string[] | null;
  /** @nullable */
  data?: number[] | null;
}
