/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 各年度保障金額
 */
export interface InsYearValue {
  /** 意外身故全殘給付 */
  acc?: number;
  /** 累積保費 */
  acuPremium?: number;
  /** 年齡 (保單健診時此處為自然年齡,每一年度保險年齡上半年與下半年會不同) */
  age?: number;
  /** 原始(投保)保額 */
  amount?: number;
  /** 融資本利和 */
  borrow?: number;
  /** 調整後保障(for 部分領回調整) */
  bwn?: number;
  /** 罹患癌症給付 */
  cancer?: number;
  /** 解約金 (若有) */
  csv?: number;
  /** 罹患重大疾病給付 */
  ddr?: number;
  /**
   * 資料類型
   * @nullable
   */
  iType?: string | null;
  /** 一般身故給付 */
  life?: number;
  /** 年度領回(年金/滿期金/年度領回金....)金額 */
  mBack?: number;
  /** 原始年度保費(原始幣別) */
  orgInsurePremium?: number;
  /** 年度保費(已換算成當地幣別) */
  premium?: number;
  /** 現價保費比率 */
  pv?: number;
  /** 減額繳清 */
  rpu?: number;
  /** 年度 */
  year?: number;
}
