/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface Int32JsonData {
  code?: number;
  data?: number;
  /** @nullable */
  message?: string | null;
  status?: boolean;
}
