/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { InterestEarning } from './interestEarning';
import type { SubModule1 } from './subModule1';

export interface InterestEarningAssets {
  /** @nullable */
  interestEarning?: InterestEarning[] | null;
  total?: SubModule1;
}
