/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { AnnuitySettingBase } from './annuitySettingBase';
import type { PManBase } from './pManBase';
import type { RpuEti } from './rpuEti';

/**
 * 建議書投保險種資料物件 (Client 的JSON格式)
 */
export interface ITMBase {
  /** 投保保險年齡 */
  age?: number;
  /** 投保保額 */
  amount?: number;
  /**
   * 投保保額文字
   * @nullable
   */
  amountString?: string | null;
  annuitySetting?: AnnuitySettingBase;
  /** 保費輸入值為0時,是否重新計算保費 */
  calcPremium?: boolean;
  /** 職業等級  1~6  :拒保 */
  cLevel?: number;
  /**
   * 保險公司中文簡稱
   * @nullable
   */
  cmpyName?: string | null;
  /**
   * 保險公司代碼
   * @nullable
   */
  cmpyNo?: string | null;
  /**
   * 被保人姓名
   * @nullable
   */
  cstmName?: string | null;
  /** 幣別匯率 */
  currencyRate?: number;
  /** 保費折扣率 */
  discountRate?: number;
  /** 險種類型 */
  dispGrade?: string;
  /**
   * 險種顯示代碼
   * @nullable
   */
  dispMark?: string | null;
  grade?: string;
  /**
   * 險種代碼
   * @nullable
   */
  iMark?: string | null;
  /**
   * 險種中文全名 計算後由系統傳回
   * @nullable
   */
  insName?: string | null;
  /** 是否為主約 */
  isMaster?: boolean;
  /**
   * 險種使用幣別代碼
   * @nullable
   */
  itemCurrency?: string | null;
  /** / 轉換為系統當地幣別的保費 */
  localPremium?: number;
  /** 繳別 0:年繳 1:半年繳 2:季繳 3:月繳 4:躉繳 */
  payment?: number;
  pMan?: PManBase;
  /** 保費 (0:由系統計算 否則依輸入保費) */
  premium?: number;
  /**
   * 保費展示字串
   * @nullable
   */
  premiumString?: string | null;
  /**
   * 保障期間
   * @nullable
   */
  protectPeriod?: string | null;
  protectYear?: number;
  /**
   * 投保日期 未填寫則依保單投保日期
   * @nullable
   */
  sDate?: string | null;
  /** 被保人性別  0:男 1:女 */
  sex?: number;
  sNo?: number;
  /** 險種特別設定(如早期MR險種的 社保/非社保...) */
  spec?: number;
  /**
   * 險種狀態 (資料庫讀入時使用,用來決定是否應納入計算)
   * @nullable
   */
  status?: string | null;
  statusInfo?: RpuEti;
  subGrade?: number;
  /** 投保對象 0:要保人  1:主被保人  2:配偶  3..8:子女 */
  target?: number;
  /**
   * 投保單位
   * @nullable
   */
  unitString?: string | null;
  /**
   * 險種幣別
   * @nullable
   */
  usedCurrencyStr?: string | null;
  /** 投保年期 */
  yearly?: number;
  /**
   * 投保年期文字
   * @nullable
   */
  yName?: string | null;
}
