/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { JsonDataData } from './jsonDataData';

export interface JsonData {
  code?: number;
  /** @nullable */
  data?: JsonDataData;
  /** @nullable */
  message?: string | null;
  status?: boolean;
}
