/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { Debt } from './debt';
import type { SubModule2 } from './subModule2';

/**
 * 負債
 */
export interface Liabilities {
  /** @nullable */
  debt?: Debt[] | null;
  total?: SubModule2;
}
