/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface LineProfile {
  /** @nullable */
  displayName?: string | null;
  /** @nullable */
  pictureUrl?: string | null;
  /** @nullable */
  statusMessage?: string | null;
  /** @nullable */
  userId?: string | null;
}
