/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { LineProfile } from './lineProfile';

export interface LineProfileJsonData {
  code?: number;
  data?: LineProfile;
  /** @nullable */
  message?: string | null;
  status?: boolean;
}
