/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 片语(值)
 */
export interface LinkLine {
  /**
   * 聯繫資料
   * @minLength 0
   * @maxLength 80
   * @nullable
   */
  cntData?: string | null;
  /**
   * 聯繫方式
   * @minLength 0
   * @maxLength 10
   * @nullable
   */
  cntType?: string | null;
  /** @nullable */
  cstmGuid?: string | null;
  /**
   * 資料類型
   * @minLength 0
   * @maxLength 12
   * @nullable
   */
  dataType?: string | null;
  guid?: string;
  /** @nullable */
  modifyDate?: string | null;
  /**
   * 列入郵件標籤列印
   * @nullable
   */
  printIt?: boolean | null;
  /**
   * 常用
   * @nullable
   */
  star?: boolean | null;
}
