/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 投保人醫療明細表的文字保險利益
 */
export interface MedicalProfit {
  /** @nullable */
  cmpyName?: string | null;
  dType?: string;
  endAge?: number;
  groupId?: number;
  /** @nullable */
  groupTxt?: string | null;
  /** @nullable */
  insName?: string | null;
  /** @nullable */
  insurcer?: string | null;
  /** @nullable */
  insurcerPKID?: string | null;
  /** @nullable */
  mark?: string | null;
  maxV?: number;
  minV?: number;
  /** @nullable */
  policyNo?: string | null;
  /** @nullable */
  protectYear?: string | null;
  startAge?: number;
}
