/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 通訊資料
 */
export interface MemberCommunication {
  /** @nullable */
  address?: string | null;
  /**
   * 公司名稱
   * @nullable
   */
  companyName?: string | null;
  /** @minLength 1 */
  eMail: string;
  /** @nullable */
  fax?: string | null;
  /**
   * 身分證字號
   * @minLength 1
   */
  id: string;
  /** @nullable */
  mobile?: string | null;
  /**
   * 中文姓名
   * @minLength 1
   */
  name: string;
  /** @minLength 1 */
  tel: string;
  /**
   * 職稱
   * @nullable
   */
  title?: string | null;
}
