/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { MemberSetting } from './memberSetting';
import type { PerformanceTargets } from './performanceTargets';

/**
 * 个人参数 + 业绩目标
 */
export interface MemberSettingAndTarget {
  settings?: MemberSetting;
  /**
   * 业绩目标
   * @nullable
   */
  targets?: PerformanceTargets[] | null;
}
