/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 个人参数
 */
export interface MemberSetting {
  /**
   * @minLength 0
   * @maxLength 24
   * @nullable
   */
  companyName?: string | null;
  /**
   * 首頁快捷
   * @minLength 0
   * @maxLength 20
   * @nullable
   */
  coverShortCut?: string | null;
  /**
   * 預設保險公司(代号)
   * @minLength 0
   * @maxLength 6
   * @nullable
   */
  defaultInsCmpy?: string | null;
  /** 修改时间 */
  editDate?: string;
  /** 修改人Id */
  editID?: number;
  /** 系統指定客戶編號 */
  isAutoCstmNo?: boolean;
  /**
   * 證照號碼
   * @minLength 0
   * @maxLength 40
   * @nullable
   */
  licenceID?: string | null;
  /**
   * LINE推播週期(0:每週一, 1:每天)
   * @nullable
   */
  linePushCycle?: number | null;
  /** 用户id */
  memberGid?: number;
  /** Line綁定訊息相關 */
  notShowMsg?: boolean;
  /** 每頁資料展示筆數 */
  pageRows?: number;
  /**
   * 照片类型
   * @minLength 0
   * @maxLength 16
   * @nullable
   */
  picMime?: string | null;
  /**
   * 我的照片
   * @nullable
   */
  picture?: string | null;
  /**
   * @minLength 0
   * @maxLength 300
   * @nullable
   */
  remark?: string | null;
  /**
   * 自定一
   * @minLength 0
   * @maxLength 10
   * @nullable
   */
  self1Name?: string | null;
  /**
   * 自定二
   * @minLength 0
   * @maxLength 10
   * @nullable
   */
  self2Name?: string | null;
  /**
   * 自定三
   * @minLength 0
   * @maxLength 10
   * @nullable
   */
  self3Name?: string | null;
  /**
   * json数据

RetirePlanSaveCmpy
RetirePlanSaveMark
RetirePlanSaveYear
FamilyFeeBy // 家庭健診保費歸屬類型 0:要保人, 1:被保人
SixCallRoutineSale
SixCallRoutineRecruit
GssType
GssID

Life // 一般身故(萬)
Accident // 意外身故(萬)
DD // 重大疾病一次給付(萬)
DSL // 失能1級保險金給付(萬)
Cancer // 初次罹癌(萬)
HT // 醫療保障實支實付限額(萬)
HL // 醫療保障住院給付(每日)

HIB_LongTermCareAccident // 長照+特傷(年)
HIB_Disability // 失能扶助金(最高)(年)
HIB_MajorIllness // 重大傷病(一次)
HIB_DD // 重疾+特傷(一次)
HIB_Life // 目前保障(年)
HIB_HospitalDailyBenefit // 住院醫療(日)
HIB_HT // 住院醫療給付(雜費)次
HIB_Surgical // 住院手術給付(最高)(次)
HIB_Accident // 意外住院(日)
HIB_Cancer // 罹患癌症(次)

ItemListPremiumType // 投保項目一覽表保費類型 0:首年度, 1:今年度
   * @minLength 0
   * @maxLength 960
   * @nullable
   */
  setting?: string | null;
  /** CloudWinner儲存空間信息 */
  storageSpace?: number;
  /**
   * CloudWinner儲存空間信息
   * @nullable
   */
  storageSpaceInfo?: string | null;
  /**
   * @minLength 0
   * @maxLength 16
   * @nullable
   */
  title?: string | null;
  /**
   * 服務網址
   * @minLength 0
   * @maxLength 36
   * @nullable
   */
  www?: string | null;
}
