/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 個人參數
 */
export interface MemberSettingDto {
  /**
   * 預設保險公司(代号)
   * @minLength 0
   * @maxLength 6
   * @nullable
   */
  defaultInsCmpy?: string | null;
  /** 系統指定客戶編號 */
  isAutoCstmNo: boolean;
  /**
   * 證照號碼
   * @minLength 0
   * @maxLength 40
   * @nullable
   */
  licenceID?: string | null;
  /**
   * LINE推播週期(0:每週一, 1:每天)
   * @nullable
   */
  linePushCycle?: number | null;
}
