/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { MemberCommunication } from './memberCommunication';

export interface MemberCommunicationJsonData {
  code?: number;
  data?: MemberCommunication;
  /** @nullable */
  message?: string | null;
  status?: boolean;
}
