/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface MessageQueue {
  /**
   * @minLength 0
   * @maxLength 200
   */
  channelID: string;
  dbID?: number;
  gNo?: number;
  /** @minLength 1 */
  message: string;
  messageType?: number;
  modifyDate?: string;
  /**
   * @minLength 0
   * @maxLength 200
   */
  pushID: string;
  pushTime?: string;
  pushType?: number;
  /**
   * @minLength 0
   * @maxLength 200
   * @nullable
   */
  remark?: string | null;
  /**
   * @minLength 0
   * @maxLength 10
   */
  sender: string;
  status?: number;
  /**
   * @minLength 0
   * @maxLength 50
   */
  title: string;
}
