/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { SubModule4 } from './subModule4';

export interface Module2 {
  /** @nullable */
  content?: SubModule4[] | null;
  subtotal?: SubModule4;
  /** @nullable */
  type?: string | null;
  /** 数据 */
  value?: number;
}
