/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 保單每月保費
 */
export interface MonthFeeInfo {
  /**
   * 保險公司簡稱
   * @nullable
   */
  cmpyName?: string | null;
  /**
   * 人名 (依要保人或被保人保費匯總而定)
   * @nullable
   */
  cName?: string | null;
  /**
   * 該保單目前每月保費
   * @nullable
   */
  fees?: number[] | null;
  /**
   * 保單號碼
   * @nullable
   */
  policyNo?: string | null;
}
