/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 每月生活費 明细 for 威盛
 */
export interface MonthExpensesDetailForWeThink {
  /** 日常開銷 */
  daily?: number;
  /** 醫療養生 */
  health?: number;
  /** 每月生活費 */
  monthExpenses?: number;
  /**
   * 生活类型
   * @nullable
   */
  monthExpensesType?: string | null;
  /** 其它支出 */
  other?: number;
  /** 進修學習 */
  study?: number;
  /** 休閒旅遊 */
  tourism?: number;
}
