/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { ObjectJsonDataData } from './objectJsonDataData';

export interface ObjectJsonData {
  code?: number;
  /** @nullable */
  data?: ObjectJsonDataData;
  /** @nullable */
  message?: string | null;
  status?: boolean;
}
