/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface OCRData {
  /** @nullable */
  aiPrase?: string | null;
  /**
   * @minLength 0
   * @maxLength 16
   * @nullable
   */
  cmpyName?: string | null;
  /**
   * @minLength 0
   * @maxLength 16
   * @nullable
   */
  cstmID?: string | null;
  /**
   * 0:policyOCR  1:台灣保險公會保險存摺PDF
   * @minLength 0
   * @maxLength 16
   */
  cstmName: string;
  editId?: number;
  id?: number;
  modifyDate?: string;
  /** @nullable */
  ocr?: string | null;
  /** @nullable */
  pic?: string | null;
  /**
   * @minLength 0
   * @maxLength 24
   * @nullable
   */
  policyId?: string | null;
  /** @nullable */
  ppljson?: string | null;
  /** @nullable */
  type?: number | null;
}
