/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 保單OCR轉換用, AI解析對應不會轉換語種,所以欄位名稱會是中文以便對應
 */
export interface OCRItem {
  /** @nullable */
  保單號碼?: string | null;
  /** @nullable */
  保額?: string | null;
  /** @nullable */
  保費?: string | null;
  /** @nullable */
  保險公司?: string | null;
  /** @nullable */
  被保人?: string | null;
  /** @nullable */
  代號?: string | null;
  /** @nullable */
  繳費年?: string | null;
  /** @nullable */
  年齡?: string | null;
  /** @nullable */
  年期?: string | null;
  /** @nullable */
  生日?: string | null;
  /** @nullable */
  投保日?: string | null;
  /** @nullable */
  險種類型?: string | null;
  /** @nullable */
  險種名稱?: string | null;
  /** @nullable */
  性別?: string | null;
  /** @nullable */
  職級?: string | null;
  /** @nullable */
  終止日?: string | null;
  /** @nullable */
  主附約?: string | null;
  /** @nullable */
  狀態?: string | null;
  /** @nullable */
  companyNo?: string | null;
  /** 標示本險種是否能成功加入建議書中做計算 */
  isOK?: boolean;
  /**
   * 保单保险公司名称
   * @nullable
   */
  policyCompName?: string | null;
}
