/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { OCRItem } from './oCRItem';

export interface OCRPolicy {
  /** @nullable */
  保單號碼?: string | null;
  /** @nullable */
  保險公司?: string | null;
  /** @nullable */
  被保人?: string | null;
  /** @nullable */
  繳別?: string | null;
  /** @nullable */
  年齡?: string | null;
  /** @nullable */
  生日?: string | null;
  /** @nullable */
  投保日?: string | null;
  /** @nullable */
  投保險種?: OCRItem[] | null;
  /** @nullable */
  性別?: string | null;
  /** @nullable */
  要保人?: string | null;
  /** @nullable */
  證件號?: string | null;
  /** @nullable */
  職級?: string | null;
  /** @nullable */
  companyNo?: string | null;
}
