/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface OpenCustomer {
  /** 客户Id */
  cstmGuid?: string;
  /**
   * 客户身份证号码
   * @minLength 0
   * @maxLength 20
   * @nullable
   */
  cstmID?: string | null;
  /** 登录用户Id */
  dbID?: number;
  /** 是否开放 */
  isOpen?: boolean;
  modifyDate?: string;
  /** 开放截止日期 */
  openDate?: string;
}
