/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 保户查询
 */
export interface OpenCstmPackageQueryModel {
  /**
   * 姓名
   * @nullable
   */
  name?: string | null;
  /** 页码 */
  pageNum?: number;
}
