/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { UserRadarItem } from './userRadarItem';
import type { ProfitGap } from './profitGap';

/**
 * 操作設定, 在資料庫裡是以 JSON 字串儲存
 */
export interface OperationSetting {
  /**
   * 保障雷達圖自定义项目（三个）
   * @nullable
   */
  customGap?: UserRadarItem[] | null;
  /** 0:家庭健診時 保費以要保人為歸屬   1:保費以被保人為歸屬 */
  familyFeeBy?: number;
  /**
   * 叡揚的店點名稱
   * @nullable
   */
  gssID?: string | null;
  /**
   * 叡揚資訊的類型, 0:無, 1:叡揚用戶
   * @nullable
   */
  gssType?: number | null;
  /** 投保項目一覽表保費類型（预设：今年度） 0:首年度, 1:今年度 */
  itemListPremiumType?: number;
  /**
   * LINE推播週期 0:每週一, 1:每天, NULL:預設為週一
   * @nullable
   */
  linePushCycle?: number | null;
  profitGap?: ProfitGap;
  /** @nullable */
  retirePlanSaveCmpy?: string | null;
  /** @nullable */
  retirePlanSaveMark?: string | null;
  /** @nullable */
  retirePlanSaveYear?: string | null;
  /** 是否显示空资料給付設定(綜合投保利益) */
  showEmpty?: boolean;
  /**
   * 六扣的增員週期設定
   * @nullable
   */
  sixCallRoutineRecruit?: string | null;
  /**
   * 六扣的銷售週期設定
   * @nullable
   */
  sixCallRoutineSale?: string | null;
  /**
   * 自定范本ID
   * @nullable
   */
  templateId?: string | null;
  /** 是否以民國年呈现 年度設定（投保項目一覽表、綜合保障明細、生存領回、每年度保費、保單總覽） */
  useTwDate?: boolean;
}
