/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { CommonSubModule } from './commonSubModule';

/**
 * 自用資產
 */
export interface OwnUseAssets {
  /**
   * 模块
   * @nullable
   */
  detail?: CommonSubModule[] | null;
  total?: CommonSubModule;
}
