/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 保單健診輸出用投保項目
 */
export interface PackageItem {
  /** 投保年齡 */
  age?: number;
  /**
   * 保額文字
   * @nullable
   */
  amount?: string | null;
  /**
   * 保險公司簡稱
   * @nullable
   */
  cmpyName?: string | null;
  /**
   * 保險公司代碼
   * @nullable
   */
  cmpyNo?: string | null;
  /**
   * 幣別
   * @nullable
   */
  currency?: string | null;
  /**
   * 目前(今年)保額
   * @nullable
   */
  currentAmount?: string | null;
  /** 目前(今年)原幣別保費 */
  currentPremium?: number;
  /** 折扣率 */
  discountRate?: number;
  /**
   * 險種展示代碼
   * @nullable
   */
  dispMark?: string | null;
  /**
   * 投保日期
   * @nullable
   */
  iDate?: string | null;
  /**
   * 險種全名
   * @nullable
   */
  insName?: string | null;
  /** 主約 or 附約 */
  isMaster?: boolean;
  /** 是否使用自然保費 */
  isNaturalPremium?: boolean;
  /** 目前(當年度)當地保費 */
  localCurrentPremium?: number;
  localPremium?: number;
  /**
   * 險種代碼
   * @nullable
   */
  mark?: string | null;
  /**
   * 繳費年數
   * @nullable
   */
  payYears?: string | null;
  /** 保費(原幣別) */
  premium?: number;
  /**
   * 保障年數
   * @nullable
   */
  protectYears?: string | null;
  /** 文字利益輸出時,標示是否被選中 */
  selected?: boolean;
  /**
   * 險種狀態
   * @nullable
   */
  status?: string | null;
  /**
   * 被保人姓名
   * @nullable
   */
  target?: string | null;
  /**
   * 投保年期
   * @nullable
   */
  yName?: string | null;
}
