/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 健診報表 投保明細表中保費呈現方式(投保當時或目前)
 */
export type PackageProfitPremium = typeof PackageProfitPremium[keyof typeof PackageProfitPremium];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PackageProfitPremium = {
  NUMBER_0: 0,
  NUMBER_1: 1,
} as const;
