/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { ViewPayLog } from './viewPayLog';
import type { ProductData } from './productData';
import type { Receipt } from './receipt';
import type { TradeData } from './tradeData';

/**
 * 購買產品明細
 */
export interface PayInfoDetail {
  /**
   * 交易明細說明(ProductData的文字版), 用#隔開
   * @nullable
   */
  orderContent?: string | null;
  payLog?: ViewPayLog;
  productData?: ProductData;
  receiptData?: Receipt;
  tradeData?: TradeData;
}
