/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface PayLogQueryModel {
  /** @nullable */
  company?: string | null;
  /** @nullable */
  endDate?: string | null;
  /** @nullable */
  orderNo?: string | null;
  pageIndex?: number;
  pageSize?: number;
  /** @nullable */
  payAmount?: number | null;
  /** @nullable */
  startDate?: string | null;
  /** @nullable */
  userGid?: number | null;
  /** @nullable */
  userName?: string | null;
}
