/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { TeamAll } from './teamAll';

/**
 * 团队绩效 + 业绩目标
 */
export interface PerformanceAndTargets {
  /**
   * 件数目标
   * @nullable
   */
  pieceCountTarget?: number[] | null;
  /**
   * 保费目标
   * @nullable
   */
  premiumTargets?: number[] | null;
  teamAll?: TeamAll;
}
