/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { PerformanceList } from './performanceList';

export interface PerformanceListListJsonData {
  code?: number;
  /** @nullable */
  data?: PerformanceList[] | null;
  /** @nullable */
  message?: string | null;
  status?: boolean;
}
