/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { PerformanceAndTargets } from './performanceAndTargets';

export interface PerformanceAndTargetsIEnumerableJsonData {
  code?: number;
  /** @nullable */
  data?: PerformanceAndTargets[] | null;
  /** @nullable */
  message?: string | null;
  status?: boolean;
}
