/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 业绩目标
 */
export interface PerformanceTargets {
  createDate?: string;
  modifyDate?: string;
  /**
   * 件数目标
   * @minLength 0
   * @maxLength 255
   */
  pieceCountTarget: string;
  /**
   * 保费目标
   * @minLength 0
   * @maxLength 255
   */
  premiumTarget: string;
  userId?: number;
  /** 年份 */
  year?: number;
}
