/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 业绩目标
 */
export interface PerformanceTargetsD {
  /** 件数目标(12个月的) */
  pieceCountTarget: number[];
  /** 保费目标(12个月的) */
  premiumTarget: number[];
  /** 年份 */
  year: number;
}
