/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 绩效 - 保单列表
 */
export interface PerformanceList {
  /**
   * 要保人
   * @nullable
   */
  applicant?: string | null;
  /**
   * 保險公司(名称)
   * @nullable
   */
  inrcmpy?: string | null;
  /**
   * 主被保人(姓名)
   * @nullable
   */
  insurer?: string | null;
  /**
   * 繳別(中文名称)
   * @nullable
   */
  payment?: string | null;
  /**
   * 投保日期
   * @nullable
   */
  policyDate?: string | null;
  /**
   * 保單號碼
   * @nullable
   */
  policyID?: string | null;
  /**
   * 總保費(新台币)
   * @nullable
   */
  premiumsLocal?: number | null;
  /**
   * 保單狀態
   * @nullable
   */
  status?: string | null;
}
