/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { PersonalBlog } from './personalBlog';
import type { PagingInfo } from './pagingInfo';

export interface PersonalBlogDataWithPageInfo {
  /** @nullable */
  datas?: PersonalBlog[] | null;
  /** @nullable */
  message?: string | null;
  pageInfo?: PagingInfo;
}
