/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { StringDic } from './stringDic';
import type { TypeData1 } from './typeData1';
import type { TypeData2 } from './typeData2';

export interface PersonData {
  /**
   * 姓名, 性別, 出生日期, 職業, 婚姻, 子女
   * @nullable
   */
  body1?: StringDic[] | null;
  /**
   * 財產明細
   * @nullable
   */
  body2?: TypeData1[] | null;
  /**
   * 客戶問題
   * @nullable
   */
  body3?: StringDic[] | null;
  /**
   * 繼承對象
   * @nullable
   */
  body4?: TypeData2[] | null;
}
