/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 我的文件 查询
 */
export interface PersonalBlogPackageQueryModel {
  /**
   * 檔案名稱
   * @nullable
   */
  fileName?: string | null;
  /** 健诊封面图片 */
  isCoverImage: boolean;
  /**
   * 連結網址
   * @nullable
   */
  linkURL?: string | null;
  /** 页码 */
  pageNum?: number;
  /**
   * 主題
   * @nullable
   */
  subject?: string | null;
}
