/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { AccountingStatisticsData } from './accountingStatisticsData';
import type { PersonData } from './personData';
import type { PiAndFa } from './piAndFa';
import type { Retire } from './retire';
import type { YearSalary } from './yearSalary';

/**
 * 財務健診
 */
export interface PersonalFinance {
  accountingStatisticsData?: AccountingStatisticsData;
  personData?: PersonData;
  piAndFa?: PiAndFa;
  retire?: Retire;
  yearSalary?: YearSalary;
}
