/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 个人博客
 */
export interface PersonalBlog {
  /**
   * 附錄
   * @nullable
   */
  appendix?: string | null;
  /**
   * 附錄ID(x)
   * @nullable
   */
  appendixID?: number | null;
  editID?: number;
  /** 企業識別碼 */
  enpterpriseID?: number;
  /**
   * 檔案名稱
   * @minLength 0
   * @maxLength 50
   * @nullable
   */
  fileName?: string | null;
  /**
   * 連結網址
   * @minLength 0
   * @maxLength 511
   * @nullable
   */
  linkURL?: string | null;
  /**
   * 檔案類型
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  mimeType?: string | null;
  modifyDate?: string;
  /**
   * 範圍 (0:我的文件, 5:自訂封面)
   * @nullable
   */
  scope?: number | null;
  /**
   * 檔案大小
   * @nullable
   */
  size?: number | null;
  sNo?: number;
  /**
   * 主題
   * @minLength 0
   * @maxLength 50
   * @nullable
   */
  subject?: string | null;
}
