/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface PersonalBlogUpdate {
  /**
   * 網址連結
   * @minLength 0
   * @maxLength 511
   * @nullable
   */
  linkUrl?: string | null;
  sNo: number;
  /**
   * 主題
   * @minLength 0
   * @maxLength 50
   */
  subject: string;
  /** 文件类型(0:文件[我的文件], 1:链接[我的文件]) */
  type: number;
}
