/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { AfterTaxIncome } from './afterTaxIncome';
import type { InheritanceTaxExemptionsDeductions } from './inheritanceTaxExemptionsDeductions';
import type { InterestEarningAssets } from './interestEarningAssets';
import type { Liabilities } from './liabilities';
import type { OwnUseAssets } from './ownUseAssets';

/**
 * 被動所得及財務分析
 */
export interface PiAndFa {
  afterTaxIncome?: AfterTaxIncome;
  inheritanceDeductions?: InheritanceTaxExemptionsDeductions;
  interestEarningAssets?: InterestEarningAssets;
  liabilities?: Liabilities;
  ownUseAssets?: OwnUseAssets;
  /** 總資產 */
  totalAssets?: number;
  /** 遺產稅課稅總額 */
  totalInheritanceTax?: number;
}
