/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { CreditCardCodeData } from './creditCardCodeData';
import type { Receipt } from './receipt';

export interface PlanDetail {
  /** @nullable */
  cancelDate?: string | null;
  creditCardCode?: CreditCardCodeData;
  /** @nullable */
  expireDate?: string | null;
  isCancel?: boolean;
  isSubscribed?: boolean;
  /** @nullable */
  modifyDate?: string | null;
  periods?: number;
  receiptData?: Receipt;
  /** @nullable */
  renewDate?: string | null;
  /** @nullable */
  type?: string | null;
}
