/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 通路險種對照
 */
export interface PlanCodeMap {
  /**
   * 企業代號
   * @minLength 0
   * @maxLength 12
   * @nullable
   */
  channel?: string | null;
  /**
   * 昇華公司代碼
   * @minLength 0
   * @maxLength 10
   * @nullable
   */
  goupCmpy?: string | null;
  /**
   * 昇華險種代碼
   * @minLength 0
   * @maxLength 10
   * @nullable
   */
  goupMark?: string | null;
  /**
   * @minLength 0
   * @maxLength 10
   */
  inAmount: string;
  inYearly?: number;
  /**
   * @minLength 0
   * @maxLength 50
   * @nullable
   */
  memo?: string | null;
  no?: number;
  /**
   * 一對多險種D代碼
   * @minLength 0
   * @maxLength 10
   * @nullable
   */
  onetomanyMark?: string | null;
  outAmount?: number;
  outYearly?: number;
  /**
   * 通路公司代碼
   * @minLength 0
   * @maxLength 10
   * @nullable
   */
  planCmpy?: string | null;
  /**
   * 通路險種名稱
   * @minLength 0
   * @maxLength 50
   * @nullable
   */
  planInsName?: string | null;
  /**
   * 通路險種代碼
   * @minLength 0
   * @maxLength 20
   * @nullable
   */
  planMark?: string | null;
  setOutAmount?: boolean;
  setOutYear?: boolean;
  unitConversion?: number;
  /** @nullable */
  updDATE?: string | null;
  /**
   * @minLength 0
   * @maxLength 16
   * @nullable
   */
  updID?: string | null;
}
