/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 通路險種對照查詢
 */
export interface PlanCodeMapPackageQueryModel {
  /**
   * 企業代號
   * @nullable
   */
  channel?: string | null;
  /**
   * 昇華公司代碼
   * @nullable
   */
  goupCmpy?: string | null;
  /**
   * 昇華險種代碼
   * @nullable
   */
  goupMark?: string | null;
  /** 页码 */
  pageNum: number;
  /**
   * 通路公司代碼
   * @nullable
   */
  planCmpy?: string | null;
  /**
   * 通路險種代碼
   * @nullable
   */
  planMark?: string | null;
}
