/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 建議書用被保人資料物件 (class obj)
 */
export interface PManBase {
  /** 保險年齡 */
  age?: number;
  /**
   * 生日
   * @nullable
   */
  birthday?: string | null;
  /** 職業等級 */
  cLevel?: number;
  /**
   * 姓名
   * @nullable
   */
  cName?: string | null;
  /**
   * 證件號碼
   * @nullable
   */
  identityNo?: string | null;
  /**
   * 人員識別碼 可為GUID值, 或使用姓名(須留意同名同姓)
   * @nullable
   */
  pkid?: string | null;
  /** 自然年齡 */
  rAge?: number;
  /**
   * 保單中的家庭身分 本人 配偶 子女.....
   * @nullable
   */
  relation?: string | null;
  /** 性別0 為男性1 為女性 */
  sex?: number;
}
