/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { Policy } from './policy';

export interface PolicyJsonData {
  code?: number;
  data?: Policy;
  /** @nullable */
  message?: string | null;
  status?: boolean;
}
