/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 保险商品排序
 */
export interface PolicyItemSort {
  guid?: string;
  /** 序號 */
  sno?: number;
}
