/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { PackageItem } from './packageItem';
import type { PManBase } from './pManBase';

/**
 * 保單健診中的保單資料
 */
export interface PolicyInfo {
  /** 意外身故全殘給付 */
  acc?: number;
  /**
   * 業務員訊息
   * @nullable
   */
  agentInfo?: string | null;
  /**
   * 顯示保額
   * @nullable
   */
  amount?: string | null;
  /**
   * 收款帳戶訊息 銀行/卡號....
   * @nullable
   */
  bankInfo?: string | null;
  /**
   * 受益人訊息
   * @nullable
   */
  benefitInfo?: string | null;
  /** 罹患癌症給付 */
  cancer?: number;
  /**
   * 繳法 信用卡/銀行匯款/收費員....
   * @nullable
   */
  chargeInfo?: string | null;
  /**
   * 保險公司中文簡稱
   * @nullable
   */
  cmpyName?: string | null;
  /**
   * 保險公司代碼
   * @nullable
   */
  cmpyNo?: string | null;
  /**
   * 保單幣別
   * @nullable
   */
  currency?: string | null;
  /**
   * 保單幣別代碼
   * @nullable
   */
  currencyCode?: string | null;
  /** 原幣別 當前匯率 */
  currencyRate?: number;
  /** 今年總保費 */
  currentPremium?: number;
  /** 年化今年總保費 */
  currentYearPremium?: number;
  /** 罹患重大疾病給付 */
  ddr?: number;
  /**
   * 保單補充說明
   * @nullable
   */
  description?: string | null;
  /**
   * 保單滿期日(終身保障實顯示為終身)
   * @nullable
   */
  expireDate?: string | null;
  /**
   * 保單健診輸出投保項目一覽表使用
   * @nullable
   */
  items?: PackageItem[] | null;
  /** 一般身故給付 */
  life?: number;
  /** 換算成本地貨幣今年總保費 */
  localCurrentPremium?: number;
  /** 換算成本地貨幣今年年化總保費 */
  localCurrentYearPremium?: number;
  /** 保單/建議書換算成本地貨幣總保費(投保時) */
  localPremium?: number;
  /** 保單/建議書換算成本地貨幣年化總保費(投保時) */
  localYearPremium?: number;
  /**
   * 繳別 年繳/半年繳....
   * @nullable
   */
  payment?: string | null;
  /**
   * 要/被保人 資料
   * @nullable
   */
  pMans?: PManBase[] | null;
  /** 投保日期 */
  policyDate?: string;
  /**
   * 保單號碼/建議書編號
   * @nullable
   */
  policyNo?: string | null;
  /**
   * 保單類型
   * @nullable
   */
  policyType?: string | null;
  /**
   * DB鍵值 (保單/建議書 datatable primary key)
   * @nullable
   */
  pplGuid?: string | null;
  /** 保單/建議書總保費(投保時) */
  premium?: number;
  /** 文字利益輸出時,標示是否被選中 */
  selected?: boolean;
  /**
   * 保單狀態
   * @nullable
   */
  status?: string | null;
  /** 保單總領回金額 */
  totalMBack?: number;
  /** 年化保單/建議書總保費(投保時) */
  yearPremium?: number;
}
