/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { Policy } from './policy';
import type { PagingInfo } from './pagingInfo';

export interface PolicyDataWithPageInfo {
  /** @nullable */
  datas?: Policy[] | null;
  /** @nullable */
  message?: string | null;
  pageInfo?: PagingInfo;
}
