/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { AnnualPolicy } from './annualPolicy';
import type { InsuranceCompanyDistribution } from './insuranceCompanyDistribution';
import type { PremiumDistribution } from './premiumDistribution';

/**
 * 保单分析 整合类
 */
export interface PolicyAnalysis {
  annual?: AnnualPolicy;
  lifeInsurance?: InsuranceCompanyDistribution;
  premium?: PremiumDistribution;
  propertyInsurance?: InsuranceCompanyDistribution;
}
