/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 保单商品
 */
export interface PolicyItemDto {
  /**
   * 異動日期
   * @nullable
   */
  adjDate?: string | null;
  /**
   * 調整後保額
   * @nullable
   */
  adjedAmount?: number | null;
  /**
   * 保額(文字)
   * @minLength 0
   * @maxLength 12
   * @nullable
   */
  amount?: string | null;
  /**
   * 幣別
   * @minLength 0
   * @maxLength 6
   * @nullable
   */
  currency?: string | null;
  /**
   * 展期到期日
   * @nullable
   */
  etiDate?: string | null;
  /**
   * 展期生存金
   * @nullable
   */
  etiMoney?: number | null;
  /**
   * 加費
   * @nullable
   */
  feeIncrease?: boolean | null;
  /**
   * 加費比例
   * @nullable
   */
  feeIncreaseRatio?: number | null;
  /**
   * 繳費期滿日
   * @nullable
   */
  finDate?: string | null;
  /** @nullable */
  guid?: string | null;
  /**
   * 保險公司(名称)
   * @minLength 0
   * @maxLength 10
   * @nullable
   */
  inrCmpy?: string | null;
  /** 投保年期 */
  inYearly?: number;
  /**
   * 險種名稱(名称)
   * @minLength 0
   * @maxLength 40
   * @nullable
   */
  itemName?: string | null;
  /**
   * 代號
   * @minLength 0
   * @maxLength 10
   * @nullable
   */
  mark?: string | null;
  /** 主约/附约 */
  master: boolean;
  /** 自然费率 */
  natureCost?: boolean;
  /** 保单Id */
  policyGuid: string;
  /** 保費(数字) */
  premium?: number;
  /**
   * 投保日期
   * @nullable
   */
  sDate?: string | null;
  /**
   * 序號
   * @nullable
   */
  sno?: number | null;
  /**
   * 是否有社保(文字)
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  spec?: string | null;
  /**
   * 險種狀態(文字)
   * @minLength 0
   * @maxLength 8
   * @nullable
   */
  status?: string | null;
  /**
   * 被保人(姓名)
   * @minLength 0
   * @maxLength 20
   */
  target: string;
  /** 被保人生日 */
  targetBirthday: string;
  /** 被保人Id */
  targetGuid: string;
  /**
   * 年金參數
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vulParm?: string | null;
  /**
   * 年期(名称)
   * @minLength 0
   * @maxLength 12
   * @nullable
   */
  yName?: string | null;
}
