/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 【主約繳費期滿】推薦名單查詢條件
 */
export interface PolicyMaturityQueryModel {
  /**
   * 保險公司名单
   * @nullable
   */
  companies?: string[] | null;
  /** 結束日期 */
  end?: string;
  pageIndex?: number;
  pageSize?: number;
  /** 開始日期 */
  start?: string;
  /** (后端设定)當前使用者 */
  userId?: number;
}
