/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export type PostMemberCentreFeedbackInsertBody = {
  files?: Blob[];
  /**
   * 問題描述
   * @minLength 0
   * @maxLength 250
   */
  reply: string;
};
