/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export type PostAuthActionLogGetByPeopleAndTimesParams = {
/**
 * 0:依人数, 1:依次数
 */
type?: number;
};
