/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export type PostMemberCentreHIBImportPolicyParams = {
/**
 * 帳號
 */
accountID?: string;
/**
 * 開始日期(yyyy-MM-DD)，若空白則預設為 1900年
 */
dateFrom?: string;
/**
 * 結束日期(yyyy-MM-DD)(含)，若空白則預設為 2050年
 */
dateTo?: string;
};
