/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export type PostAuthMemberInformationUploadBatchCreateParams = {
entId?: number;
roleParam?: string;
check?: boolean;
descriptionType?: number;
parameter?: string;
};
