/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export type PostMemberCentrePlanCodeMapGetPageListParams = {
/**
 * false: 分页查询, true:导出Excel文件
 */
output?: boolean;
};
