/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export type PostProposalGuildPolicyParams = {
/**
 * PDF密碼
 */
password?: string;
/**
 * 客戶身分證號
 */
cstmId?: string;
/**
 * 客戶中文姓名
 */
cstmName?: string;
/**
 * 業務員主鍵值
 */
agentId?: number;
};
