/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export type PostMemberCentreSetUnBindedParams = {
/**
 * 解綁哪個通路
 */
provideType?: string;
/**
 * 要解綁的id
 */
userid?: number;
};
