/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export type PostAi365ToolsBusinessFundVideoSaveBody = {
  guid?: string;
  imageFile?: Blob[];
  /**
   * 影片名稱
   * @minLength 0
   * @maxLength 50
   */
  name: string;
  /** 文稿 */
  text: string;
  /** 影片網址 */
  url: string;
};
