/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export type Ppltype = typeof Ppltype[keyof typeof Ppltype];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Ppltype = {
  NUMBER_0: 0,
  NUMBER_6: 6,
  NUMBER_7: 7,
  NUMBER_8: 8,
  NUMBER_10: 10,
  NUMBER_MINUS_1: -1,
} as const;
