/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 保費分布統計
 */
export interface PremiumDistribution {
  /** @nullable */
  data?: string[] | null;
  /** @nullable */
  title?: string[] | null;
}
