/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { ProductInfo } from './productInfo';

/**
 * 商品明細
 */
export interface ProductDetail {
  /** 合計金額(新版不用) */
  amount?: number;
  extraPeriods?: number;
  /**
   * 商品代號
   * @nullable
   */
  id?: string | null;
  info?: ProductInfo;
  /**
   * 商品名稱(新結構)
   * @nullable
   */
  name?: string | null;
  /** 現在金額 */
  nowMoney?: number;
  /** 原始金額 */
  orgMoney?: number;
  /** 期數 */
  periods?: number;
  /**
   * 期間類型(y/m/d)
   * @nullable
   */
  periodType?: string | null;
  /** 數量 */
  quantity?: number;
  /** 被選取 */
  selected?: boolean;
}
