/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface ProductInfo {
  /**
   * 商品代號
   * @nullable
   */
  id?: string | null;
  /**
   * 其他資訊
   * @nullable
   */
  jsonData?: string | null;
  /**
   * 商品名稱
   * @nullable
   */
  name?: string | null;
  /** 價格 */
  price?: number;
}
