/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 定期險保障期滿名單搜尋
 */
export interface ProfitExpireQueryModel {
  /** 結束日期 */
  end?: string;
  pageIndex?: number;
  pageSize?: number;
  /** 開始日期 */
  start?: string;
  /** (后端设定)當前使用者 */
  userId?: number;
}
