/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 保障雷達圖應備預設值
 */
export interface ProfitGap {
  /** 意外身故 */
  Accident?: number;
  /** 初次罹癌 */
  Cancer?: number;
  /** 重大疾病 */
  DD?: number;
  /** 失能1級保險金給付 */
  DSL?: number;
  /** 意外住院(日) */
  HIB_Accident?: number;
  /** 罹患癌症(次) */
  HIB_Cancer?: number;
  /** 重疾+特傷(一次) */
  HIB_DD?: number;
  /** 失能補助金(最高)(年) */
  HIB_Disability?: number;
  /** 住院醫療(日) */
  HIB_HospitalDailyBenefit?: number;
  /** 住院醫療給付(雜費)(次) */
  HIB_HT?: number;
  /** 目前保障(年) */
  HIB_Life?: number;
  /** 長照+特傷(年) */
  HIB_LongTermCareAccident?: number;
  /** 重大傷病(一次) */
  HIB_MajorIllness?: number;
  /** 住院手術給付(最高)(次) */
  HIB_Surgical?: number;
  /** 醫療保障住院給付(每日) */
  HL?: number;
  /** 醫療保障實支實付限額 */
  HT?: number;
  /** 一般身故 */
  Life?: number;
}
