/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { Proposal } from './proposal';

export interface ProposalJsonData {
  code?: number;
  data?: Proposal;
  /** @nullable */
  message?: string | null;
  status?: boolean;
}
