/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 險種每人年度保費
 * @nullable
 */
export type ProposalProfitItemYearPremium = {[key: string]: number[] | null} | null;
