/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 建议书查询
 */
export interface ProposalPackageQueryModel {
  /** @nullable */
  cstmGuid?: string | null;
  /**
   * 客戶姓名
   * @nullable
   */
  cstmName?: string | null;
  /**
   * 客户编号
   * @nullable
   */
  cstmNo?: string | null;
  /**
   * 建議書名稱
   * @nullable
   */
  description?: string | null;
  /**
   * 類型 (PPL:綜合建議書, PSN:個人健診, IRR:年化報酬率, JFF:個人財務健診, RTP:退休規劃, SHT:外幣保單)
   * @minLength 1
   */
  dType: string;
  /** @nullable */
  editId?: number | null;
  /**
   * 证件号码
   * @nullable
   */
  id?: string | null;
  /**
   * 險種代號
   * @nullable
   */
  mainMark?: string | null;
  /**
   * 手机号码
   * @nullable
   */
  mobile?: string | null;
  /** 页码 */
  pageNum?: number;
}
