/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { InputPPLObj } from './inputPPLObj';
import type { PersonalFinance } from './personalFinance';

/**
 * for swagger use
 */
export interface ProposalWhole {
  /**
   * 要保人
   * @minLength 0
   * @maxLength 20
   * @nullable
   */
  applicant?: string | null;
  /**
   * 生日
   * @nullable
   */
  birthday?: string | null;
  /** @nullable */
  comples?: number | null;
  contact?: InputPPLObj;
  contactObj?: PersonalFinance;
  /**
   * 被保人Id
   * @nullable
   */
  cstmGuid?: string | null;
  /**
   * 被保人姓名
   * @minLength 0
   * @maxLength 20
   * @nullable
   */
  cstmName?: string | null;
  /**
   * 建議書名稱
   * @minLength 0
   * @maxLength 80
   * @nullable
   */
  description?: string | null;
  /**
   * 類型 (PPL:綜合建議書, PSN:個人健診, IRR:年化報酬率, JFF:個人財務健診, RTP:退休規劃, SHT:外幣保單)
   * @minLength 0
   * @maxLength 6
   * @nullable
   */
  dType?: string | null;
  editID?: number;
  guid?: string;
  /**
   * 險種代號
   * @minLength 0
   * @maxLength 12
   * @nullable
   */
  mainMark?: string | null;
  /**
   * 婚姻狀況
   * @nullable
   */
  marry?: string | null;
  modifyDate?: string;
  /**
   * 姓名
   * @nullable
   */
  name?: string | null;
  /** @nullable */
  prompts?: number | null;
  /**
   * 性別
   * @nullable
   */
  sex?: string | null;
  /**
   * 狀態
   * @minLength 0
   * @maxLength 16
   * @nullable
   */
  status?: string | null;
  /** @nullable */
  suggestion?: string | null;
  /**
   * 職稱
   * @nullable
   */
  title?: string | null;
  /**
   * @minLength 0
   * @maxLength 8
   * @nullable
   */
  ver?: string | null;
}
