/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface ProposalCstm {
  /**
   * 生日
   * @nullable
   */
  birthday?: string | null;
  /**
   * 客戶編號
   * @nullable
   */
  cstmNo?: string | null;
  /** Customer主键 */
  guid?: string;
  /**
   * 婚姻狀況
   * @nullable
   */
  marry?: string | null;
  /**
   * 姓名
   * @nullable
   */
  name?: string | null;
  /**
   * 性別
   * @nullable
   */
  sex?: string | null;
  /**
   * 職稱
   * @nullable
   */
  title?: string | null;
}
