/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { Receipt } from './receipt';

export interface ReceiptItem {
  _Receipt?: Receipt;
  /** @nullable */
  type?: string | null;
  userID?: number;
}
