/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 購買者發票資訊
 */
export interface Receipt {
  /**
   * 發票抬頭
   * @nullable
   */
  company?: string | null;
  /**
   * 發票抬頭
   * @nullable
   */
  companyName?: string | null;
  /**
   * 手機
   * @nullable
   */
  mobile?: string | null;
  /**
   * 營業處
   * @nullable
   */
  office?: string | null;
  /**
   * E-MAIL
   * @nullable
   */
  receiptEmail?: string | null;
  /**
   * Inv2 一般消費者 Inv3  公司報帳發票
   * @nullable
   */
  receiptType?: string | null;
  /**
   * 持卡人姓名
   * @nullable
   */
  userName?: string | null;
  /**
   * 郵遞區號 + 縣市 +區域 +地址
   * @nullable
   */
  vatAddr?: string | null;
  /** @nullable */
  vatNumber?: string | null;
  /**
   * 載具條碼
   * @nullable
   */
  vehicleNumber?: string | null;
}
