/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * RefreshToken
 */
export interface RefreshTokenUser {
  /**
   * 用户名
   * @minLength 1
   */
  identityNo: string;
  /**
   * RefreshToken
   * @minLength 1
   */
  refreshToken: string;
}
