/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface ResetPasswordByAdmin {
  /**
   * 使用者信箱
   * @nullable
   */
  customEmail?: string | null;
  /**
   * 使用者名稱
   * @nullable
   */
  customName?: string | null;
  /**
   * 使用者電話
   * @nullable
   */
  customTel?: string | null;
  /**
   * 驗證碼
   * @nullable
   */
  password?: string | null;
  /**
   * 使用者ID
   * @nullable
   */
  userID?: string | null;
}
