/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { AlreadyPrepared } from './alreadyPrepared';
import type { BeforeRetirement } from './beforeRetirement';
import type { AfterRetirement } from './afterRetirement';

export interface RetirePlanPage {
  /** 目前年齡 */
  age: number;
  /** [显示] 退休後可領回之生存年金 */
  annuityBenefit?: number;
  /**
   * 客户姓名
   * @minLength 1
   */
  cstmName: string;
  /** 假設延後規劃 */
  delayYears1: number;
  /**
   * 计划名称
   * @nullable
   */
  description?: string | null;
  /** 已備儲蓄金(整筆) */
  hadRtValue?: number;
  /** 已備儲蓄金預定報酬率 */
  hadRtValueRate?: number;
  /** 預估通膨率 */
  inflationRate?: number;
  /** [显示] 退休前可領回之儲蓄險 */
  insuranceBenefit?: number;
  /** 預計找尋工具報酬率 */
  invToolRate1: number;
  /** [显示] 退休後預計生活年期 N 年 */
  invToRtYears1?: number;
  /** 預計規劃至 */
  lifeAge: number;
  /** 基本退休生活每月所需 */
  monthExpenses1: number;
  /** 优质退休生活每月所需 */
  monthExpenses2: number;
  /** 預計投入規劃期間 */
  planYears1: number;
  /** [显示] 退休已備總額(一般退休) */
  prepareForRT1?: number;
  /** [显示] 退休已備總額(優質退休) */
  prepareForRT2?: number;
  /** [显示] 已備定期定額投資 */
  regularBenefit?: number;
  /** [显示] 合計退休時總金額 */
  regularSum?: number;
  /** 退休年齡 */
  retireAge: number;
  /** [显示] 基本退休生活 */
  retireAmount1?: number;
  /** [显示] 退休時所需總額(一般退休) */
  retireAmount1S?: number;
  /** [显示] 優質退休生活 */
  retireAmount2?: number;
  /** [显示] 退休時所需總額(優質退休) */
  retireAmount2S?: number;
  /** [显示] 合計退休時總金額 */
  retireSum?: number;
  /** [显示] 需要為自己準備x年的退休金 */
  retYear?: number;
  /** [显示] 合計退休時總金額 */
  savingSum?: number;
  /**
   * 已備定期定額投資
   * @nullable
   */
  setting1?: AlreadyPrepared[] | null;
  /**
   * 退休前可領回之儲蓄險
   * @nullable
   */
  setting2?: BeforeRetirement[] | null;
  /**
   * 退休後可領回之生存年金
   * @nullable
   */
  setting3?: AfterRetirement[] | null;
  /**
   * 性別
   * @nullable
   */
  sexuality?: string | null;
  /**
   * [显示][string] 屆時退休金缺口(一般退休)
   * @nullable
   */
  shortfall1?: string | null;
  /**
   * [显示][string] 屆時退休金缺口(優質退休)
   * @nullable
   */
  shortfall2?: string | null;
  /** [显示] 每月應備 */
  shortfallMonth1?: number;
  /** [显示] 每月應備 */
  shortfallMonth2?: number;
  /** [显示] 基本退休生活 */
  shortfallYear1?: number;
  /** [显示] 優質退休生活 */
  shortfallYear2?: number;
}
