/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { RtAnnuityInfo } from './rtAnnuityInfo';
import type { RetirementInfo } from './retirementInfo';
import type { RtInsInfo } from './rtInsInfo';
import type { MonthExpensesDetailForWeThink } from './monthExpensesDetailForWeThink';
import type { RTBaseInfo } from './rTBaseInfo';
import type { RtRegularInvestInfo } from './rtRegularInvestInfo';

/**
 * 退休计划
 */
export interface RetirePlan {
  /** 年金收益 */
  annuityBenefit?: number;
  annuityInv?: RtAnnuityInfo;
  /** 延遲規劃年數 */
  delayYears?: number;
  /** 延遲規劃年數 */
  delayYears1?: number;
  /** 延遲規劃年數 */
  delayYears2?: number;
  /** @nullable */
  description?: string | null;
  /** 預估月領退休金 */
  forecastRtMonthValue?: number;
  /** 預估一次退休金(如:勞退.勞保/公保) */
  forecastRtOnceValue?: number;
  /** 現在已備金額 */
  hadRtValue?: number;
  /** 現在已備金額退休收益 */
  hadRtValueProfit?: number;
  /** 現在已備金額投報率 */
  hadRtValueRate?: number;
  infoAnnuity?: RetirementInfo;
  infoFarmer?: RetirementInfo;
  infoGov?: RetirementInfo;
  infoLabor?: RetirementInfo;
  infoRetirementNew?: RetirementInfo;
  infoRetirementOld?: RetirementInfo;
  infoSoldier?: RetirementInfo;
  insrInv?: RtInsInfo;
  /** 儲蓄險收益 */
  insuranceBenefit?: number;
  /** 理想投資工具報酬率 */
  invToolRate?: number;
  /** 理想投資工具報酬率 */
  invToolRate1?: number;
  /** 理想投資工具報酬率2 */
  invToolRate2?: number;
  /** 以上報酬率累積至退休年度 */
  invToRtYears?: number;
  /** 以上報酬率累積至退休年度 */
  invToRtYears1?: number;
  /** 以上報酬率累積至退休年度 */
  invToRtYears2?: number;
  meDetailForWeThink?: MonthExpensesDetailForWeThink;
  /** 每月生活費 - 無憂生活 */
  monthExpenses1?: number;
  /** 每月生活費 - 神仙生活 */
  monthExpenses2?: number;
  /** 預設幾年完成規劃 */
  planYears?: number;
  /** 預設幾年完成規劃 */
  planYears1?: number;
  /** 預設幾年完成規劃 */
  planYears2?: number;
  /** 退休應備金額 */
  prepareForRT?: number;
  rbInfo?: RTBaseInfo;
  /** 定時定額收益 */
  regularBenefit?: number;
  regularInv?: RtRegularInvestInfo;
  /** 退休準備所需總金額 - 無憂生活 (使用年金現值法計算) */
  retireAmount1?: number;
  /** 退休準備所需總金額 - 神仙生活 (使用年金現值法計算) */
  retireAmount2?: number;
  /** 退休後每月所需生活費(無憂生活) */
  retireMonthExpenses1?: number;
  /** 退休後每月所需生活費(神仙生活) */
  retireMonthExpenses2?: number;
  rtpGuid?: string;
  /** 退休缺口 */
  shortfall1?: number;
  /** 退休缺口2 */
  shortfall2?: number;
}
