/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface Role {
  /** @nullable */
  key?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  type?: number | null;
}
