/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 文件
 */
export interface RootFileInfo {
  /** @nullable */
  name?: string | null;
  /**
   * url(Azure blobName/ wwwroot url)
   * @nullable
   */
  path?: string | null;
  /** 0:自定义(来自Azure),1:系统默认(来自wwwroot) */
  type?: number;
}
