/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 保單辦理  減額繳清/展期 的變數結構
 */
export interface RpuEti {
  /** // 展期時間   年.日 */
  eti?: string;
  /** 展期生存金 */
  ets?: number;
  /** 減額繳清後保額 */
  setAmount?: number;
  /** 減額繳清/展期  開始的保單年度/ */
  setDate?: string;
  /** 0:未設定　1:減額繳清  2:展期  3:豁免 */
  sType?: number;
}
