/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface Rss {
  /** @nullable */
  description?: string | null;
  /** @nullable */
  link?: string | null;
  pubDate?: string;
  /** @nullable */
  title?: string | null;
}
