/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { RtAnnuity } from './rtAnnuity';

/**
 * 退休規劃 年金規劃試算
 */
export interface RtAnnuityInfo {
  /** @nullable */
  annuities?: RtAnnuity[] | null;
}
