/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 財務規劃  退休規劃  被保人基本設定
 */
export interface RTBaseInfo {
  /** 目前年齡 */
  age?: number;
  /**
   * 姓名
   * @nullable
   */
  cstmName?: string | null;
  /** 通貨膨脹 */
  inflationRate?: number;
  /** 投資報酬率 */
  investRate?: number;
  /** 預計規劃至幾歲（預設為平均壽命） */
  lifeAge?: number;
  /** 預計退休年齡  本人/配偶 */
  retireAge?: number;
  /** 性別 */
  sex?: number;
  /** 平均餘命(退休後) */
  yearsAfterRetire?: number;
}
