/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 退休規劃 每一筆現有保單退休金
 */
export interface RtInsurance {
  /** 退休時收益金額 */
  benefitAmount?: number;
  /** 滿期金(解約金) */
  edAmount?: number;
  /** 到期年度 */
  expiredYear?: number;
  /**
   * 保單名稱
   * @nullable
   */
  insrName?: string | null;
  /** 再投資報酬率 */
  refillRate?: number;
}
