/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { RtInsurance } from './rtInsurance';

/**
 * 退休規劃 現有保單退休金試算
 */
export interface RtInsInfo {
  /** @nullable */
  insurances?: RtInsurance[] | null;
}
