/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { RtRegularInvest } from './rtRegularInvest';

/**
 * 退休規劃 定時定額投資收益 試算
 */
export interface RtRegularInvestInfo {
  /** @nullable */
  invests?: RtRegularInvest[] | null;
}
