/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 行程報表(活动图)类
 */
export interface ScheduleReportDiagram {
  /** @nullable */
  progress?: string | null;
  timeSpend?: number;
}
