/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { Schedule } from './schedule';
import type { PagingInfo } from './pagingInfo';

export interface ScheduleDataWithPageInfo {
  /** @nullable */
  datas?: Schedule[] | null;
  /** @nullable */
  message?: string | null;
  pageInfo?: PagingInfo;
}
