/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 行程報表类[显示]
 */
export interface ScheduleReportHtml {
  /** @nullable */
  c0?: string | null;
  /** @nullable */
  c1?: string | null;
  /** @nullable */
  c10?: string | null;
  /** @nullable */
  c11?: string | null;
  /** @nullable */
  c12?: string | null;
  /** @nullable */
  c13?: string | null;
  /** @nullable */
  c14?: string | null;
  /** @nullable */
  c15?: string | null;
  /** @nullable */
  c16?: string | null;
  /** @nullable */
  c17?: string | null;
  /** @nullable */
  c18?: string | null;
  /** @nullable */
  c19?: string | null;
  /** @nullable */
  c2?: string | null;
  /** @nullable */
  c20?: string | null;
  /** @nullable */
  c3?: string | null;
  /** @nullable */
  c4?: string | null;
  /** @nullable */
  c5?: string | null;
  /** @nullable */
  c6?: string | null;
  /** @nullable */
  c7?: string | null;
  /** @nullable */
  c8?: string | null;
  /** @nullable */
  c9?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  score?: string | null;
  /** @nullable */
  setDate?: string | null;
  /** @nullable */
  total?: string | null;
}
