/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface Schedule {
  /** 全天 */
  allDay?: boolean;
  /**
   * 增員
   * @nullable
   */
  appointmentLayout?: string | null;
  /**
   * 標題
   * @minLength 0
   * @maxLength 80
   * @nullable
   */
  caption?: string | null;
  /**
   * 備註
   * @minLength 0
   * @maxLength 350
   * @nullable
   */
  content?: string | null;
  /**
   * 客戶姓名
   * @minLength 0
   * @maxLength 30
   * @nullable
   */
  cstm?: string | null;
  /**
   * 客户Id
   * @nullable
   */
  cstmGuid?: string | null;
  /** @nullable */
  editID?: number | null;
  /**
   * 結束日期
   * @nullable
   */
  endTime?: string | null;
  /**
   * 評估
   * @nullable
   */
  estimate?: number | null;
  /**
   * 狀態(進行中, 完成, 取消)
   * @minLength 0
   * @maxLength 10
   * @nullable
   */
  finish?: string | null;
  guid?: string;
  /**
   * 圖片
   * @nullable
   */
  imageIndex?: number | null;
  /**
   * 等級
   * @minLength 0
   * @maxLength 2
   * @nullable
   */
  level?: string | null;
  /** @nullable */
  modifyDate?: string | null;
  /**
   * 進度
   * @minLength 0
   * @maxLength 20
   * @nullable
   */
  progress?: string | null;
  /**
   * 重複拜訪
   * @nullable
   */
  recurrencePattern?: string | null;
  /**
   * 結果
   * @nullable
   */
  result?: number | null;
  /**
   * 業務員Id
   * @minLength 0
   * @maxLength 30
   * @nullable
   */
  setID?: string | null;
  /**
   * 來源
   * @minLength 0
   * @maxLength 20
   * @nullable
   */
  source?: string | null;
  /** 開始日期 */
  startTime?: string;
  /** 類型(0:訓練, 1:銷售, 2:增員, 3:服務, 6:其他, 999:全部) */
  type?: number;
}
