/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { SelectListGroup } from './selectListGroup';

export interface SelectListItem {
  disabled?: boolean;
  group?: SelectListGroup;
  selected?: boolean;
  /** @nullable */
  text?: string | null;
  /** @nullable */
  value?: string | null;
}
