/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface SelectItem {
  /** @nullable */
  isSelected?: boolean | null;
  /** @nullable */
  text?: string | null;
  /** @nullable */
  value?: string | null;
}
