/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface SetSmsQuery {
  /**
   * 簡訊帳號
   * @nullable
   */
  smsId?: string | null;
  /**
   * 簡訊密碼
   * @nullable
   */
  smsPwd?: string | null;
  /**
   * 使用者ID
   * @nullable
   */
  userId?: string | null;
}
