/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 險種比較 文字利益結果
 */
export interface SimpleTxtProfit {
  /** @nullable */
  profitText?: string | null;
  type?: string;
  /** @nullable */
  val?: string | null;
}
