/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 用户信息(简易)
 */
export interface SimpleUser {
  userID?: number;
  /**
   * 中文姓名
   * @nullable
   */
  userName?: string | null;
}
