/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { StringStringIDictionaryJsonDataData } from './stringStringIDictionaryJsonDataData';

export interface StringStringIDictionaryJsonData {
  code?: number;
  /** @nullable */
  data?: StringStringIDictionaryJsonDataData;
  /** @nullable */
  message?: string | null;
  status?: boolean;
}
