/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * @nullable
 */
export type StringStringIDictionaryJsonDataData = {[key: string]: string} | null;
