/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 子模块
 */
export interface SubModule4 {
  /**
   * 種類
   * @nullable
   */
  currency?: string | null;
  /** 所得稅 */
  incomeTax?: number;
  /** 被動所得 */
  passiveIncome?: number;
  /** 稅後所得 */
  taxAfterIncome?: number;
}
