/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 子模块
 */
export interface SubModule2 {
  /** 貸款金額(元) */
  cash?: number;
  /** 利息支出(元/月) */
  interest?: number;
  /**
   * 類別
   * @nullable
   */
  item?: string | null;
  /** 利率(%) */
  rate?: number;
}
