/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 訂閱
 */
export interface Subscription {
  dbID?: number;
  modifyDate?: string;
  /** @nullable */
  subscriptionModel?: string | null;
}
