/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface SubscriptionsItem {
  /** @nullable */
  cancelDate?: string | null;
  /** @nullable */
  expireDate?: string | null;
  isCancel?: boolean;
  isSubscribed?: boolean;
  /** @nullable */
  modifyDate?: string | null;
  /** @nullable */
  name?: string | null;
  periods?: number;
  /** @nullable */
  renewDate?: string | null;
  /** @nullable */
  type?: string | null;
}
