/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { SubscriptionsItem } from './subscriptionsItem';

export interface SubscriptionsByAdmin {
  /** @nullable */
  subscriptionItems?: SubscriptionsItem[] | null;
  userId?: number;
}
