/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 表数据变更日志
 */
export interface TableLog {
  /**
   * 变更后
   * @nullable
   */
  after?: string | null;
  /**
   * 变更前
   * @nullable
   */
  before?: string | null;
  gid?: string;
  /**
   * 证件号码
   * @minLength 0
   * @maxLength 12
   */
  memberId: string;
  modifyDate?: string;
  /**
   * 表名
   * @minLength 0
   * @maxLength 10
   */
  tableName: string;
  /**
   * 目标Id
   * @minLength 0
   * @maxLength 30
   */
  targetId: string;
}
