/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface TableLogQm {
  /**
   * 编辑日期(止)
   * @nullable
   */
  endDate?: string | null;
  /**
   * 证件号码
   * @nullable
   */
  memberId?: string | null;
  /** 页码 */
  pageNum: number;
  /**
   * 编辑日期(起)
   * @nullable
   */
  startDate?: string | null;
  /**
   * 表名
   * @nullable
   */
  tableName?: string | null;
  /**
   * 目标Id
   * @nullable
   */
  targetId?: string | null;
}
