/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface Tag {
  /**
   * 标签
   * @minLength 0
   * @maxLength 50
   */
  caption: string;
  /** @nullable */
  color?: number | null;
  /** @nullable */
  editID?: number | null;
  /** @nullable */
  modifyDate?: string | null;
  /**
   * 使用人數
   * @nullable
   */
  numberOfPeopleUsed?: number | null;
  tagGid?: number;
}
