/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 保单查询
 */
export interface TagPackageQueryModel {
  /**
   * 标签查询
   * @nullable
   */
  caption?: string | null;
  pageNum?: number;
}
