/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface TeamData {
  /** 件数 */
  count?: number;
  /**
   * 總保費
   * @nullable
   */
  premiumsLocal?: number | null;
  /**
   * 年月
   * @nullable
   */
  yearMonth?: string | null;
}
