/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { TeamAndCalendarData } from './teamAndCalendarData';

export interface TeamAndCalendarDataJsonData {
  code?: number;
  data?: TeamAndCalendarData;
  /** @nullable */
  message?: string | null;
  status?: boolean;
}
