/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 團隊客戶
 */
export interface TeamMemberPackageQueryModel {
  /**
   * 团队成员id
   * @nullable
   */
  editId?: number[] | null;
  /**
   * 客戶等級: 判定等級
   * @nullable
   */
  grade?: string | null;
  /**
   * 婚姻狀況
   * @nullable
   */
  marry?: string | null;
  /**
   * 姓名
   * @nullable
   */
  name?: string | null;
  /** 页码 */
  pageNum?: number;
  /**
   * 客戶等級: 進行階段
   * @nullable
   */
  phase?: string | null;
  /**
   * 性別
   * @nullable
   */
  sex?: string | null;
}
