/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { TeamData } from './teamData';

export interface TeamAll {
  /** @nullable */
  data?: TeamData[] | null;
  userId?: number;
  /**
   * 中文姓名
   * @nullable
   */
  userName?: string | null;
}
