/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 包含每一險種各項給付的文字保險利益
 */
export interface TextProfit {
  /**
   * 本人給付數值
   * @nullable
   */
  c1?: string | null;
  /**
   * 配偶給付數值
   * @nullable
   */
  c2?: string | null;
  /**
   * 子女給付數值
   * @nullable
   */
  c3?: string | null;
  /**
   * 保險公司中文簡稱
   * @nullable
   */
  companyName?: string | null;
  /**
   * 該給付利益所屬的保險公司
   * @nullable
   */
  companyNo?: string | null;
  /**
   * 給付說明文字
   * @nullable
   */
  description?: string | null;
  /** 顯示屬性標示 */
  dspLevel?: string;
  /** 群組利益編號 */
  groupId?: number;
  /**
   * 類型
   * @nullable
   */
  iType?: string | null;
  /**
   * 險種代碼
   * @nullable
   */
  mark?: string | null;
  /**
   * 給付期間(依保單年度 0:起 1:止， 期間設定在ins_prft)
   * @nullable
   */
  period?: number[] | null;
  /**
   * 保單號碼
   * @nullable
   */
  policyID?: string | null;
}
