/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { ProfitGroup } from './profitGroup';

/**
 * 每一被保人的群組綜合投保利益,每個人給付數字放在profitGroup.values中 包含當年度與 最小~最大 的給付說明
 * @nullable
 */
export type TFamilyProfitGroupProfits = {[key: string]: ProfitGroup} | null;
