/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { InsYearValue } from './insYearValue';

/**
 * 每個人的各年度各項保費及給付保障金額
 * @nullable
 */
export type TFamilyProfitYearValues = {[key: string]: InsYearValue[] | null} | null;
