/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { ProfitGroup } from './profitGroup';

/**
 * 每個人在每張保單(只要該保單中有該人的保障)中的各項投保利益
 * @nullable
 */
export type TFamilyProfitPersonalGroupProfits = {[key: string]: {[key: string]: ProfitGroup} | null} | null;
