/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { TFamilyProfitFamilyValues } from './tFamilyProfitFamilyValues';
import type { TFamilyProfitGroupProfits } from './tFamilyProfitGroupProfits';
import type { MedicalProfit } from './medicalProfit';
import type { MonthFeeInfo } from './monthFeeInfo';
import type { InsPackParam } from './insPackParam';
import type { TFamilyProfitPersonalGroupProfits } from './tFamilyProfitPersonalGroupProfits';
import type { PManBase } from './pManBase';
import type { PolicyInfo } from './policyInfo';
import type { TFamilyProfitSpecProfits } from './tFamilyProfitSpecProfits';
import type { TFamilyProfitTextProfits } from './tFamilyProfitTextProfits';
import type { TFamilyProfitYearValues } from './tFamilyProfitYearValues';

/**
 * 用以記錄家庭保單健診中保險利益的詳細資料的類
 */
export interface TFamilyProfit {
  /**
   * 各年度領回金額(含生存金,年金...) 每一欄為一個被保人之年度金額 [人,年度] (維度0=人數+1, 最後一列為當年度合計值)
   * @nullable
   */
  dtMBack?: number[][] | null;
  /**
   * 計算中的錯誤訊息
   * @nullable
   */
  errorMessage?: string | null;
  /**
   * 附加資料 (Json格式 for 報表列印)
   * @nullable
   */
  extrnData?: string | null;
  /**
   * 每個人的各年度一般身故/意外/癌症保障金額
   * @nullable
   */
  familyValues?: TFamilyProfitFamilyValues;
  /**
   * 每一被保人的群組綜合投保利益,每個人給付數字放在profitGroup.values中 包含當年度與 最小~最大 的給付說明
   * @nullable
   */
  groupProfits?: TFamilyProfitGroupProfits;
  insPackType?: number;
  /** 是否計算成功(false:失敗,沒有計算結果,失敗原因表現在errorMessage, true:可以產出計算結果,可能會有部分錯誤訊息,呈現在errorMessage) */
  isSuccess?: boolean;
  /**
   * 本家庭/群組 健診的標題文字
   * @nullable
   */
  mainCName?: string | null;
  /**
   * 本家庭/群組 健診的標題文字
   * @nullable
   */
  mainName?: string | null;
  /** @nullable */
  mainPKID?: string | null;
  /** 最高繳費年期 */
  maxPayYear?: number;
  /** 最高保障年期 */
  maxProtectYear?: number;
  /**
   * 醫療明細表(有GroupNo的給付項目)的文字型保險利益集合
   * @nullable
   */
  medicalTxtPrfts?: MedicalProfit[] | null;
  /**
   * 每一被保人各保單每月保費
   * @nullable
   */
  monthFee?: MonthFeeInfo[] | null;
  param?: InsPackParam;
  /**
   * 每個人在每張保單(只要該保單中有該人的保障)中的各項投保利益
   * @nullable
   */
  personalGroupProfits?: TFamilyProfitPersonalGroupProfits;
  /**
   * 被保人列表
   * @nullable
   */
  pManList?: PManBase[] | null;
  /**
   * 保單列表
   * @nullable
   */
  policies?: PolicyInfo[] | null;
  /**
   * 包含每一張保單每一個險種(不管有沒有群組編號)的各項險種特色
   * @nullable
   */
  specProfits?: TFamilyProfitSpecProfits;
  /** 最早投保年齡 */
  startAge?: number;
  /** 本家庭健診最早開始年度 */
  startYear?: number;
  /**
   * 包含每一張保單每一個險種(不管有沒有群組編號)的各項文字給付說明
   * @nullable
   */
  textProfits?: TFamilyProfitTextProfits;
  /** 總領回金額 */
  totalMBack?: number;
  /**
   * 各年度保費 [人,年度] (維度0=人數+1, 最後一列為當年度合計值)
   * @nullable
   */
  yearFee?: number[][] | null;
  /**
   * 每個人的各年度各項保費及給付保障金額
   * @nullable
   */
  yearValues?: TFamilyProfitYearValues;
}
