/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { TextProfit } from './textProfit';

/**
 * 包含每一張保單每一個險種(不管有沒有群組編號)的各項文字給付說明
 * @nullable
 */
export type TFamilyProfitTextProfits = {[key: string]: TextProfit[] | null} | null;
