/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 每個人的各年度一般身故/意外/癌症保障金額
 * @nullable
 */
export type TFamilyProfitFamilyValues = {[key: string]: number[][] | null} | null;
