/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 收入合計
 */
export interface TotalRevenue {
  /** 稅前月收入合計 */
  cash1?: number;
  /** 稅前年收入合計 */
  cash2?: number;
  /** 所得稅扣繳稅額 */
  cash3?: number;
  /** 稅後收入合計 */
  cash4?: number;
  /** 每年儲蓄額 */
  cash5?: number;
  /** 儲蓄率 */
  cash6?: number;
}
