/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { ProfitGroup } from './profitGroup';

/**
 * 群組綜合投保利益 包含當年度與 最小~最大 的給付說明 key:GroupNo
 * @nullable
 */
export type TPersonalProfitGroupProfits = {[key: string]: ProfitGroup} | null;
