/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 交易資訊
 */
export interface TradeData {
  /** @nullable */
  cardNo?: string | null;
  /**
   * 備註
   * @nullable
   */
  memo?: string | null;
  /** @nullable */
  returnTime?: string | null;
  sendTime?: string;
  /** @nullable */
  tradeMsg?: string | null;
}
