/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { BooleanDic } from './booleanDic';

export interface TypeData2 {
  /** @nullable */
  detail?: BooleanDic[] | null;
  /** @nullable */
  type?: string | null;
}
