/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { StringDic } from './stringDic';

export interface TypeData1 {
  /** @nullable */
  detail?: StringDic[] | null;
  /** @nullable */
  type?: string | null;
}
