/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { DoubleDic } from './doubleDic';

export interface TypeData3 {
  /** @nullable */
  detail?: DoubleDic[] | null;
  /** 小計 */
  subtotal?: number;
  /** @nullable */
  type?: string | null;
}
