/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface UserProfit {
  /** 加乘保額 */
  byVAL?: boolean;
  /**
   * 公司代號
   * @minLength 0
   * @maxLength 8
   */
  cmpy: string;
  /** @nullable */
  companyName?: string | null;
  editID?: number;
  /** 歸類至 */
  groupNo?: number;
  guid?: string;
  /**
   * 商品代號
   * @minLength 0
   * @maxLength 10
   */
  mark: string;
  /**
   * 給付說明
   * @minLength 0
   * @maxLength 32
   */
  profitContent: string;
  /** 給付類型(1:一般身故, 2:意外身故, 3:重大疾病, 4:癌症身故, 5:其他) */
  profitType?: number;
  /** 給付金額 */
  profitVAL?: number;
}
