/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 用户查询
 */
export interface UserInfoRolePackageQueryModel {
  /**
   * 角色
   * @nullable
   */
  addValueType?: string[] | null;
  /**
   * 取消日(訖)
   * @nullable
   */
  cancelDateEnd?: string | null;
  /**
   * 取消日(起)
   * @nullable
   */
  cancelDateStart?: string | null;
  /**
   * 创建日(訖)
   * @nullable
   */
  createDateEnd?: string | null;
  /**
   * 创建日(起)
   * @nullable
   */
  createDateStart?: string | null;
  /**
   * E-Mail
   * @nullable
   */
  email?: string | null;
  /**
   * 账号验证(0:未验证,1:已验证)
   * @nullable
   */
  emailConfirmed?: number | null;
  /**
   * 企業
   * @nullable
   */
  enterpriseGID?: number | null;
  /**
   * 有效期(訖)
   * @nullable
   */
  expireDateEnd?: string | null;
  /**
   * 有效期(起)
   * @nullable
   */
  expireDateStart?: string | null;
  /**
   * 身分證字號
   * @nullable
   */
  identityNo?: string | null;
  /** 页码 */
  pageNum?: number;
  /**
   * 手機
   * @nullable
   */
  tel?: string | null;
  /**
   * 中文姓名
   * @nullable
   */
  userName?: string | null;
}
