/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { AddValueNew } from './addValueNew';

export interface UserInfo {
  /**
   * 地址
   * @minLength 0
   * @maxLength 40
   * @nullable
   */
  address?: string | null;
  /**
   * 角色有效期
   * @nullable
   */
  addValueList?: AddValueNew[] | null;
  /**
   * 角色有效期
   * @nullable
   */
  addValueListBefore?: AddValueNew[] | null;
  /** 是否同意被指导 */
  allowDirector?: boolean;
  /**
   * [为了兼容旧版winner]
   * @nullable
   */
  appUser?: boolean | null;
  /**
   * [为了兼容旧版winner]
   * @nullable
   */
  availableDate?: string | null;
  /**
   * 出生日期
   * @nullable
   */
  birthday?: string | null;
  /**
   * x
   * @nullable
   */
  branchGid?: number | null;
  /**
   * 公司名稱
   * @minLength 0
   * @maxLength 24
   * @nullable
   */
  companyName?: string | null;
  /**
   * ?
   * @minLength 0
   * @maxLength 32
   * @nullable
   */
  comparID?: string | null;
  createDate?: string;
  /**
   * 直屬主管
   * @minLength 0
   * @maxLength 40
   * @nullable
   */
  directorID?: string | null;
  /** @nullable */
  editID?: number | null;
  /**
   * EditorMemberId
   * @nullable
   */
  editorMemberId?: string | null;
  /**
   * E-Mail
   * @minLength 0
   * @maxLength 50
   * @nullable
   */
  email?: string | null;
  emailConfirmed?: boolean;
  /** 企業 */
  enterpriseGID?: number;
  /**
   * @minLength 0
   * @maxLength 16
   * @nullable
   */
  fax?: string | null;
  /**
   * 保單存摺同意聲明時間
   * @nullable
   */
  guildAgreement?: string | null;
  /**
   * 身分證字號
   * @minLength 0
   * @maxLength 20
   * @nullable
   */
  identityNo?: string | null;
  /**
   * 職稱
   * @nullable
   */
  jobTitle?: string | null;
  /**
   * 密码修改日期
   * @nullable
   */
  lastPWDChangeDate?: string | null;
  /**
   * Line姓名
   * @nullable
   */
  lineName?: string | null;
  /**
   * Google/LINE/MSOpenId
   * @nullable
   */
  loginProvider?: string | null;
  /**
   * 备注
   * @minLength 0
   * @maxLength 500
   * @nullable
   */
  memo?: string | null;
  modifyDate?: string;
  /**
   * 密碼
   * @minLength 0
   * @maxLength 96
   */
  passwordHash: string;
  /**
   * @minLength 0
   * @maxLength 48
   * @nullable
   */
  refreshtoken?: string | null;
  /**
   * 续约
   * @nullable
   */
  renewContract?: boolean | null;
  /**
   * 性别
   * @minLength 0
   * @maxLength 2
   * @nullable
   */
  sex?: string | null;
  /** 显示付费按钮 */
  showPayButton?: boolean;
  /**
   * x
   * @minLength 0
   * @maxLength 50
   * @nullable
   */
  signature?: string | null;
  /**
   * 簡訊帳號
   * @minLength 0
   * @maxLength 32
   * @nullable
   */
  smsid?: string | null;
  /**
   * [为了兼容旧版winner]
   * @minLength 0
   * @maxLength 16
   * @nullable
   */
  smsno?: string | null;
  /**
   * 簡訊密碼
   * @minLength 0
   * @maxLength 20
   * @nullable
   */
  smspwd?: string | null;
  /**
   * [为了兼容旧版winner]
   * @nullable
   */
  subRole?: number | null;
  /**
   * 手機
   * @minLength 0
   * @maxLength 16
   * @nullable
   */
  tel?: string | null;
  /**
   * 職稱
   * @minLength 0
   * @maxLength 16
   * @nullable
   */
  title?: string | null;
  /** @nullable */
  tokenExpire?: string | null;
  userID?: number;
  /**
   * x
   * @minLength 0
   * @maxLength 20
   * @nullable
   */
  userLifeID?: string | null;
  /**
   * 中文姓名
   * @minLength 0
   * @maxLength 20
   */
  userName: string;
}
