/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { UserRadarItem } from './userRadarItem';
import type { UserRadarGroupValueScaler } from './userRadarGroupValueScaler';
import type { OperationSetting } from './operationSetting';
import type { UserGroupText } from './userGroupText';

/**
 * 雷达图参数
 */
export interface UserRadar {
  /**
   * 雷达图自订项目选项
(給付項目1、給付項目2、給付項目3)
   * @nullable
   */
  customGapItems?: UserRadarItem[] | null;
  /**
   * 给付项目数值倍数(key: GroupID, value: multiBy)
<br>由于 JSON 序列化时不包含 static 字段或属性，所以在这里映射一次。
   * @nullable
   */
  readonly groupValueScaler?: UserRadarGroupValueScaler;
  /**
   * 雷达图给付项目
   * @nullable
   */
  items?: UserRadarItem[] | null;
  operation?: OperationSetting;
  /**
   * 自訂項號組合範本
   * @nullable
   */
  templates?: UserGroupText[] | null;
  userId?: number;
}
