/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 自定义-范本
 */
export interface UserGroupText {
  /**
   * 自訂項號(分号分隔)
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  extendGroupText?: string | null;
  gid?: string;
  /**
   * 排除项Id(分号分隔)
   * @nullable
   */
  groupTextSetting?: string | null;
  /**
   * 模式名稱
   * @minLength 0
   * @maxLength 15
   */
  modeName: string;
  modifyDate?: string;
  userId?: number;
}
