/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 给付项目数值倍数(key: GroupID, value: multiBy)
<br>由于 JSON 序列化时不包含 static 字段或属性，所以在这里映射一次。
 * @nullable
 */
export type UserRadarGroupValueScaler = {[key: string]: number} | null;
