/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface UserPhrase {
  /**
   * 內容
   * @minLength 0
   * @maxLength 50
   */
  content: string;
  editID?: number;
  modifyDate?: string;
  no?: number;
  /**
   * 類型(11:通訊錄電話, 12:通訊錄地址, 13:通訊錄郵件)
   * @minLength 0
   * @maxLength 4
   */
  type: string;
}
