/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface UserItemD {
  /**
   * 公司代號
   * @minLength 1
   */
  cmpy: string;
  guid?: string;
  /**
   * 商品名稱
   * @minLength 1
   */
  itemName: string;
  /**
   * 商品代號
   * @minLength 1
   */
  mark: string;
  /**
   * 繳費年期
   * @minLength 1
   */
  paymentYear: string;
  /**
   * 保障年期
   * @minLength 1
   */
  protectYear: string;
  /**
   * 單位
   * @minLength 1
   */
  unit: string;
}
