/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface UserGroupTextD {
  /**
   * 自訂項號(分号分隔)
   * @nullable
   */
  extendGroupText?: string | null;
  /** @nullable */
  gid?: string | null;
  /**
   * 排除项Id(分号分隔)
   * @nullable
   */
  groupTextSetting?: string | null;
  /**
   * 模式名稱
   * @minLength 1
   */
  modeName: string;
}
