/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 更新密碼
 */
export interface UserPassword {
  /**
   * 新密码
   * @minLength 10
   * @maxLength 20
   */
  newPassword: string;
  /**
   * 原密码
   * @minLength 1
   */
  password: string;
}
