/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { UserProfit } from './userProfit';

export interface UserItem {
  /**
   * 保障利益
   * @nullable
   */
  buyer?: number | null;
  /**
   * 險別
   * @minLength 0
   * @maxLength 2
   */
  class: string;
  /**
   * 公司代號
   * @minLength 0
   * @maxLength 8
   */
  cmpy: string;
  /**
   * 醫療類利益
   * @nullable
   */
  ddr?: number | null;
  editID?: number;
  /**
   * 終身
   * @nullable
   */
  fullLife?: boolean | null;
  guid?: string;
  /** 序號 */
  inc?: number;
  /**
   * 商品名稱
   * @minLength 0
   * @maxLength 30
   */
  itemName: string;
  /**
   * 數值
   * @nullable
   */
  keyinVal?: boolean | null;
  /**
   * 商品代號
   * @minLength 0
   * @maxLength 10
   */
  mark: string;
  /** 最高保額 */
  maxVAL?: number;
  /** 最低保額 */
  minVAL?: number;
  /**
   * 平準/自然
   * @nullable
   */
  natureCost?: boolean | null;
  /**
   * 繳費年期
   * @minLength 0
   * @maxLength 30
   */
  paymentYear: string;
  /**
   * 一次性給付
   * @nullable
   */
  payOnes?: boolean | null;
  /**
   * 保障
   * @nullable
   */
  prot?: number | null;
  /**
   * 保障年期
   * @minLength 0
   * @maxLength 30
   */
  protectYear: string;
  /**
   * 停售
   * @nullable
   */
  saled?: boolean | null;
  /**
   * 類型
   * @nullable
   */
  type?: number | null;
  /**
   * 單位
   * @minLength 0
   * @maxLength 10
   */
  unit: string;
  /**
   * 自定义-给付利益
   * @nullable
   */
  userProfitList?: UserProfit[] | null;
}
