/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

/**
 * 保户登入
 */
export interface UserLogin {
  /**
   * 验证码
   * @minLength 1
   */
  code: string;
  /**
   * 用户名
   * @minLength 1
   */
  identityNo: string;
  /**
   * 密碼
   * @minLength 1
   */
  password: string;
  /**
   * 记住我
   * @nullable
   */
  rememberMe?: boolean | null;
}
