/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { UserRadar } from './userRadar';

export interface UserRadarJsonData {
  code?: number;
  data?: UserRadar;
  /** @nullable */
  message?: string | null;
  status?: boolean;
}
