/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { VCustomerHealthCheckDataWithPageInfo } from './vCustomerHealthCheckDataWithPageInfo';

export interface VCustomerHealthCheckDataWithPageInfoJsonData {
  code?: number;
  data?: VCustomerHealthCheckDataWithPageInfo;
  /** @nullable */
  message?: string | null;
  status?: boolean;
}
