/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface VCustomerFamily {
  /** @nullable */
  birthday?: string | null;
  editId?: number;
  guid?: string;
  /** @nullable */
  modifyDate?: string | null;
  /**
   * @minLength 0
   * @maxLength 50
   */
  name: string;
  /**
   * @minLength 0
   * @maxLength 1
   */
  relationship: string;
  /**
   * @minLength 0
   * @maxLength 2
   * @nullable
   */
  sex?: string | null;
}
