/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { VCustomerFamily } from './vCustomerFamily';
import type { PagingInfo } from './pagingInfo';

export interface VCustomerFamilyDataWithPageInfo {
  /** @nullable */
  datas?: VCustomerFamily[] | null;
  /** @nullable */
  message?: string | null;
  pageInfo?: PagingInfo;
}
