/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface VFamilyLink2 {
  /** @nullable */
  age?: number | null;
  /** @nullable */
  birthday?: string | null;
  cLevel?: number;
  customerId?: string;
  /** @nullable */
  english?: string | null;
  /** @nullable */
  familyNo?: string | null;
  fId?: string;
  /** @nullable */
  id?: string | null;
  /** @nullable */
  idType?: string | null;
  /** @nullable */
  memo?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  relate?: string | null;
  /** @nullable */
  sex?: string | null;
  type?: number;
}
