/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface VFeedback {
  /** @nullable */
  answer?: string | null;
  createDate?: string;
  /**
   * @minLength 0
   * @maxLength 50
   * @nullable
   */
  eMail?: string | null;
  /** @nullable */
  fileName?: string | null;
  /**
   * @minLength 0
   * @maxLength 20
   * @nullable
   */
  id?: string | null;
  /**
   * @minLength 0
   * @maxLength 16
   * @nullable
   */
  mobile?: string | null;
  /** @nullable */
  modifyDate?: string | null;
  /**
   * @minLength 0
   * @maxLength 20
   */
  name: string;
  /**
   * @minLength 0
   * @maxLength 250
   */
  reply: string;
  sNo?: number;
  /** @nullable */
  status?: number | null;
}
