/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { ViewPayFinish } from './viewPayFinish';
import type { PagingInfo } from './pagingInfo';

export interface ViewPayFinishDataWithPageInfo {
  /** @nullable */
  datas?: ViewPayFinish[] | null;
  /** @nullable */
  message?: string | null;
  pageInfo?: PagingInfo;
}
