/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface ViewInsMBackInfo {
  /** @nullable */
  companyName?: string | null;
  /** @nullable */
  insurer?: string | null;
  /** @nullable */
  insurerGuid?: string | null;
  /** @nullable */
  itemName?: string | null;
  /** @nullable */
  mark?: string | null;
  payDate?: string;
  payValue?: number;
  policyGuid?: string;
  /** @nullable */
  policyNo?: string | null;
  setID?: number;
}
