/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface ViewPayLog {
  amount?: number;
  /**
   * @minLength 0
   * @maxLength 4000
   * @nullable
   */
  company?: string | null;
  /** @nullable */
  expireDate?: string | null;
  /** @nullable */
  model?: string | null;
  /**
   * @minLength 0
   * @maxLength 14
   */
  orderNo: string;
  /**
   * @minLength 0
   * @maxLength 4
   */
  orderType: string;
  payGuid?: string;
  /**
   * @minLength 0
   * @maxLength 4000
   * @nullable
   */
  receiptEmail?: string | null;
  /**
   * @minLength 0
   * @maxLength 4000
   * @nullable
   */
  receiptType?: string | null;
  /** @nullable */
  returnDate?: string | null;
  sendDate?: string;
  /** @nullable */
  tradeStatus?: number | null;
  /**
   * @minLength 0
   * @maxLength 15
   * @nullable
   */
  tradeType?: string | null;
  userGid?: number;
  /**
   * @minLength 0
   * @maxLength 20
   * @nullable
   */
  userLifeID?: string | null;
  /**
   * @minLength 0
   * @maxLength 20
   */
  userName: string;
  /**
   * @minLength 0
   * @maxLength 4000
   * @nullable
   */
  vehicleNumber?: string | null;
}
