/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { ViewInsMBackInfo } from './viewInsMBackInfo';
import type { PagingInfo } from './pagingInfo';

export interface ViewInsMBackInfoDataWithPageInfo {
  /** @nullable */
  datas?: ViewInsMBackInfo[] | null;
  /** @nullable */
  message?: string | null;
  pageInfo?: PagingInfo;
}
