/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface ViewPolicyConsultations {
  accident?: number;
  /** @nullable */
  age?: number | null;
  ahi?: number;
  /** @nullable */
  birthday?: string | null;
  cancer?: number;
  /** @nullable */
  caption?: string | null;
  /** @nullable */
  cstmGuid?: string | null;
  dbr?: number;
  ddr?: number;
  dsl?: number;
  editID?: number;
  guid?: string;
  hi?: number;
  hs?: number;
  /** @nullable */
  id?: string | null;
  life?: number;
  lifeGift?: number;
  loseMonth?: number;
  loseYear?: number;
  ltc?: number;
  /** @nullable */
  modifyDate?: string | null;
  /** @nullable */
  name?: string | null;
  sdr?: number;
  /** @nullable */
  setID?: string | null;
  /** @nullable */
  sex?: string | null;
}
