/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { ViewPolicyConsultations } from './viewPolicyConsultations';
import type { PagingInfo } from './pagingInfo';

export interface ViewPolicyConsultationsDataWithPageInfo {
  /** @nullable */
  datas?: ViewPolicyConsultations[] | null;
  /** @nullable */
  message?: string | null;
  pageInfo?: PagingInfo;
}
