/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface ViewProfitExpire {
  /** @nullable */
  companyName?: string | null;
  /** @nullable */
  editID?: number | null;
  /** @nullable */
  expDate?: string | null;
  guid?: string;
  /** @nullable */
  insurer?: string | null;
  /** @nullable */
  insurerGuid?: string | null;
  /** @nullable */
  itemName?: string | null;
  /** @nullable */
  mark?: string | null;
  policyGuid?: string;
  /** @nullable */
  policyID?: string | null;
}
