/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { ViewPayLog } from './viewPayLog';
import type { PagingInfo } from './pagingInfo';

export interface ViewPayLogDataWithPageInfo {
  /** @nullable */
  datas?: ViewPayLog[] | null;
  /** @nullable */
  message?: string | null;
  pageInfo?: PagingInfo;
}
