/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface VOpenCustomer {
  /** @nullable */
  birthday?: string | null;
  /** @nullable */
  editID?: number | null;
  /** @nullable */
  guid?: string | null;
  /**
   * @minLength 0
   * @maxLength 20
   * @nullable
   */
  id?: string | null;
  isOpen?: boolean;
  /**
   * @minLength 0
   * @maxLength 16
   * @nullable
   */
  mobile?: string | null;
  /** @nullable */
  modifyDate?: string | null;
  /**
   * @minLength 0
   * @maxLength 50
   * @nullable
   */
  name?: string | null;
  openDate?: string;
  /**
   * @minLength 0
   * @maxLength 2
   * @nullable
   */
  sex?: string | null;
}
