/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { VOpenCustomer } from './vOpenCustomer';
import type { PagingInfo } from './pagingInfo';

export interface VOpenCustomerDataWithPageInfo {
  /** @nullable */
  datas?: VOpenCustomer[] | null;
  /** @nullable */
  message?: string | null;
  pageInfo?: PagingInfo;
}
