/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { VProposal } from './vProposal';
import type { PagingInfo } from './pagingInfo';

export interface VProposalDataWithPageInfo {
  /** @nullable */
  datas?: VProposal[] | null;
  /** @nullable */
  message?: string | null;
  pageInfo?: PagingInfo;
}
