/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface VProposal {
  /**
   * @minLength 0
   * @maxLength 20
   * @nullable
   */
  applicant?: string | null;
  /** @nullable */
  birthday?: string | null;
  /**
   * @minLength 0
   * @maxLength 1
   */
  contact: string;
  /** @nullable */
  cstmGuid?: string | null;
  /**
   * @minLength 0
   * @maxLength 20
   * @nullable
   */
  cstmName?: string | null;
  /**
   * @minLength 0
   * @maxLength 10
   * @nullable
   */
  cstmNo?: string | null;
  /**
   * @minLength 0
   * @maxLength 80
   * @nullable
   */
  description?: string | null;
  /**
   * @minLength 0
   * @maxLength 6
   * @nullable
   */
  dType?: string | null;
  editId?: number;
  guid?: string;
  /**
   * @minLength 0
   * @maxLength 20
   * @nullable
   */
  id?: string | null;
  /**
   * @minLength 0
   * @maxLength 12
   * @nullable
   */
  mainMark?: string | null;
  /**
   * @minLength 0
   * @maxLength 16
   * @nullable
   */
  mobile?: string | null;
  modifyDate?: string;
  /**
   * @minLength 0
   * @maxLength 2
   * @nullable
   */
  sex?: string | null;
  /**
   * @minLength 0
   * @maxLength 16
   * @nullable
   */
  status?: string | null;
  /**
   * @minLength 0
   * @maxLength 8
   * @nullable
   */
  ver?: string | null;
}
