/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { VUserInfoRole } from './vUserInfoRole';
import type { PagingInfo } from './pagingInfo';

export interface VUserInfoRoleDataWithPageInfo {
  /** @nullable */
  datas?: VUserInfoRole[] | null;
  /** @nullable */
  message?: string | null;
  pageInfo?: PagingInfo;
}
