/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */

export interface VUserInfoRole {
  /**
   * @minLength 0
   * @maxLength 40
   * @nullable
   */
  address?: string | null;
  /**
   * @minLength 0
   * @maxLength 12
   * @nullable
   */
  addValueType?: string | null;
  allowDirector?: boolean;
  /** @nullable */
  appUser?: boolean | null;
  /** @nullable */
  availableDate?: string | null;
  /** @nullable */
  birthday?: string | null;
  /** @nullable */
  branchGid?: number | null;
  /** @nullable */
  cancelDate?: string | null;
  /**
   * @minLength 0
   * @maxLength 24
   * @nullable
   */
  companyName?: string | null;
  /**
   * @minLength 0
   * @maxLength 32
   * @nullable
   */
  comparID?: string | null;
  createDate?: string;
  /**
   * @minLength 0
   * @maxLength 40
   * @nullable
   */
  directorID?: string | null;
  /** @nullable */
  editID?: number | null;
  /**
   * @minLength 0
   * @maxLength 50
   * @nullable
   */
  email?: string | null;
  emailConfirmed?: boolean;
  enterpriseGID?: number;
  /** @nullable */
  expireDate?: string | null;
  /**
   * @minLength 0
   * @maxLength 16
   * @nullable
   */
  fax?: string | null;
  /** @nullable */
  guildAgreement?: string | null;
  /**
   * @minLength 0
   * @maxLength 20
   * @nullable
   */
  identityNo?: string | null;
  /** @nullable */
  lastPWDChangeDate?: string | null;
  /**
   * @minLength 0
   * @maxLength 500
   * @nullable
   */
  memo?: string | null;
  modifyDate?: string;
  /**
   * @minLength 0
   * @maxLength 96
   */
  passwordHash: string;
  /**
   * @minLength 0
   * @maxLength 48
   * @nullable
   */
  refreshtoken?: string | null;
  /**
   * @minLength 0
   * @maxLength 2
   * @nullable
   */
  sex?: string | null;
  /**
   * @minLength 0
   * @maxLength 50
   * @nullable
   */
  signature?: string | null;
  /**
   * @minLength 0
   * @maxLength 32
   * @nullable
   */
  smsid?: string | null;
  /**
   * @minLength 0
   * @maxLength 16
   * @nullable
   */
  smsno?: string | null;
  /**
   * @minLength 0
   * @maxLength 20
   * @nullable
   */
  smspwd?: string | null;
  /** @nullable */
  subRole?: number | null;
  /**
   * @minLength 0
   * @maxLength 16
   * @nullable
   */
  tel?: string | null;
  /**
   * @minLength 0
   * @maxLength 16
   * @nullable
   */
  title?: string | null;
  /** @nullable */
  tokenExpire?: string | null;
  userID?: number;
  /**
   * @minLength 0
   * @maxLength 20
   * @nullable
   */
  userLifeID?: string | null;
  /**
   * @minLength 0
   * @maxLength 20
   */
  userName: string;
}
