/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * WnrAPI
 * OpenAPI spec version: 1.0
 */
import type { TypeData3 } from './typeData3';
import type { TotalRevenue } from './totalRevenue';

export interface YearSalary {
  /** @nullable */
  body1?: TypeData3[] | null;
  total?: TotalRevenue;
}
